load("//rules/typescript:index.bzl", "ts_library")

ts_library(
    name = "careers",
    srcs = ["careers.tsx"],
    deps = [
        "//website/src/css:common.module.css",
        "//website/src/pages:careers.module.css",
        "@npm//@theme/Layout",
        "@npm//@types/react",
        "@npm//lucide-react",
        "@npm//react",
    ],
)

ts_library(
    name = "cli",
    srcs = ["cli.tsx"],
    deps = [
        "//website/src/components/cta",
        "//website/src/components/hero",
        "//website/src/components/terminal",
        "//website/src/css:common.module.css",
        "@npm//@theme/Layout",
        "@npm//@types/react",
        "@npm//github.com",
        "@npm//react",
        "@npm//tslib",
    ],
)

ts_library(
    name = "contact",
    srcs = ["contact.tsx"],
    deps = [
        "//website/src/css:common.module.css",
        "//website/src/pages:contact.module.css",
        "//website/src/util:message",
        "@npm//@theme/Layout",
        "@npm//@types/react",
        "@npm//lucide-react",
        "@npm//react",
    ],
)

ts_library(
    name = "features",
    srcs = ["features.tsx"],
    deps = [
        "//website/src/components/cta",
        "//website/src/components/hero",
        "//website/src/components/terminal",
        "//website/src/css:common.module.css",
        "@npm//@theme/Layout",
        "@npm//@types/react",
        "@npm//react",
        "@npm//tslib",
    ],
)

ts_library(
    name = "index",
    srcs = ["index.tsx"],
    deps = [
        "//website/src/components/brands",
        "//website/src/components/cta",
        "//website/src/components/enterprise",
        "//website/src/components/hero",
        "//website/src/components/integrations",
        "//website/src/components/logs",
        "//website/src/components/oss",
        "//website/src/components/quote",
        "//website/src/components/rbe",
        "//website/src/css:common.module.css",
        "@npm//@theme/Layout",
        "@npm//@types/react",
        "@npm//react",
    ],
)

ts_library(
    name = "open-source-repos",
    srcs = ["open-source-repos.tsx"],
    deps = [
        "//website/src/components/oss:oss-list",
        "//website/src/css:common.module.css",
        "//website/src/pages:contact.module.css",
        "//website/src/pages:open-source-repos.module.css",
        "//website/src/util:message",
        "@npm//@theme/Layout",
        "@npm//@types/react",
        "@npm//react",
    ],
)

ts_library(
    name = "plugins",
    srcs = ["plugins.tsx"],
    deps = [
        "//website/src/components/cta",
        "//website/src/components/hero",
        "//website/src/css:common.module.css",
        "//website/src/pages:contact.module.css",
        "//website/src/pages:plugins.module.css",
        "//website/src/util:clipboard",
        "//website/src/util:message",
        "@npm//@theme/Layout",
        "@npm//@types/react",
        "@npm//lucide-react",
        "@npm//react",
    ],
)

ts_library(
    name = "pricing",
    srcs = ["pricing.tsx"],
    deps = [
        "//website/src/components/cta",
        "//website/src/css:common.module.css",
        "//website/src/pages:pricing.module.css",
        "@npm//@theme/Layout",
        "@npm//@types/react",
        "@npm//lucide-react",
        "@npm//react",
    ],
)

ts_library(
    name = "remote-cache",
    srcs = ["remote-cache.tsx"],
    deps = [
        "//website/src/components/cta",
        "//website/src/components/globe",
        "//website/src/components/hero",
        "//website/src/css:common.module.css",
        "@npm//@theme/Layout",
        "@npm//@types/react",
        "@npm//react",
    ],
)

ts_library(
    name = "remote-execution",
    srcs = ["remote-execution.tsx"],
    deps = [
        "//website/src/components/cta",
        "//website/src/components/hero",
        "//website/src/components/terminal",
        "//website/src/css:common.module.css",
        "@npm//@theme/Layout",
        "@npm//@types/react",
        "@npm//react",
    ],
)

ts_library(
    name = "request-demo",
    srcs = ["request-demo.tsx"],
    deps = [
        "//website/src/css:common.module.css",
        "//website/src/pages:contact.module.css",
        "//website/src/util:message",
        "@npm//@theme/Layout",
        "@npm//@types/react",
        "@npm//react",
    ],
)

ts_library(
    name = "request-quote",
    srcs = ["request-quote.tsx"],
    deps = [
        "//website/src/css:common.module.css",
        "//website/src/pages:contact.module.css",
        "//website/src/util:message",
        "@npm//@theme/Layout",
        "@npm//@types/react",
        "@npm//react",
    ],
)

ts_library(
    name = "team",
    srcs = ["team.tsx"],
    deps = [
        "//website/src/css:common.module.css",
        "//website/src/pages:team.module.css",
        "@npm//@theme/IdealImage",
        "@npm//@theme/Layout",
        "@npm//@types/react",
        "@npm//react",
    ],
)

ts_library(
    name = "ui",
    srcs = ["ui.tsx"],
    deps = [
        "//website/src/components/cta",
        "//website/src/components/hero",
        "//website/src/css:common.module.css",
        "@npm//@theme/Layout",
        "@npm//@types/react",
        "@npm//react",
    ],
)

ts_library(
    name = "workflows",
    srcs = ["workflows.tsx"],
    deps = [
        "//website/src/components/cta",
        "//website/src/components/hero",
        "//website/src/css:common.module.css",
        "@npm//@theme/Layout",
        "@npm//@types/react",
        "@npm//react",
    ],
)
