load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "quarantine",
    testonly = 1,
    srcs = ["quarantine.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/testutil/quarantine",
    visibility = ["//visibility:public"],
)
