load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "xcontext",
    srcs = ["xcontext.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/experimental/mcp/xcontext",
    visibility = ["//visibility:public"],
)
