load("//rules/typescript:index.bzl", "ts_library")

ts_library(
    name = "logs",
    srcs = ["logs.tsx"],
    deps = [
        "//website/src/components/logs:logs.module.css",
        "//website/src/css:common.module.css",
        "@npm//@theme/IdealImage",
        "@npm//@types/react",
        "@npm//react",
    ],
)
