load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "mockstore",
    srcs = ["mockstore.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/testutil/mockstore",
    visibility = ["//visibility:public"],
)
