load("//rules/typescript:index.bzl", "ts_library")

ts_library(
    name = "integrations",
    srcs = ["integrations.tsx"],
    deps = [
        "//website/src/components/integrations:integrations.module.css",
        "//website/src/css:common.module.css",
        "@npm//@theme/IdealImage",
        "@npm//@types/react",
        "@npm//react",
    ],
)
