app:
  no_default_user_group: true
  create_group_per_user: true
  add_user_to_domain_group: true
  code_editor_enabled: true
  default_redis_target: "localhost:6379"
  log_level: debug
database:
  data_source: "sqlite3:///tmp/buildbuddy-enterprise_%{USER}.db"
storage:
  ttl_seconds: 86400 # One day in seconds.
  disk:
    root_directory: /tmp/buildbuddy_enterprise
cache:
  in_memory: true
  raft:
    listen_addr: "127.0.0.1:9201" # gossip
    http_addr: "127.0.0.1:9301" # raft HTTP
    grpc_addr: "127.0.0.1:9401" # filecache backhaul
    join: ["127.0.0.1:9201", "127.0.0.1:9202", "127.0.0.1:9203"]
auth:
  enable_anonymous_usage: true
  oauth_providers:
    - issuer_url: "https://accounts.google.com"
      client_id: "${BB_DEV_OAUTH_CLIENT_ID}"
      client_secret: "${BB_DEV_OAUTH_CLIENT_SECRET}"
github:
  client_id: "${BB_DEV_GITHUB_CLIENT_ID}"
  client_secret: "${BB_DEV_GITHUB_CLIENT_SECRET}"
