# N.B. This file is bundled and distributed in the enterprise docker image.
# It should not contain any secrets. Test the image if you change it!
app:
  events_api_url: "grpc://localhost:1985"
  cache_api_url: "grpc://localhost:1985"
  default_redis_target: "localhost:6379"
storage:
  ttl_seconds: 0 # No TTL (yet).
  disk:
    root_directory: "/buildbuddy/blobs/"
cache:
  disk:
    root_directory: "/buildbuddy/cache/"
auth:
  enable_self_auth: true
