auth:
  remote:
    target: "grpc://localhost:1985"
  reparse_jwts: false
cache:
  tree_cache_splitting: true
  pebble:
    name: "pebble_cache"
    active_key_version: 5
    root_directory: /tmp/${USER}-buildbuddy-enterprise-pebble-cache
cache_proxy:
  remote_cache: "grpc://localhost:1985"
  remote_hit_tracker:
    target: "grpc://localhost:1985"
  cache_action_results: true
crypter:
  remote_target: "grpc://localhost:1985"
