package clickhouse_test

import (
	"context"
	"encoding/hex"
	"slices"
	"strings"
	"testing"
	"time"

	"github.com/buildbuddy-io/buildbuddy/server/remote_cache/digest"
	"github.com/buildbuddy-io/buildbuddy/server/testutil/testenv"
	"github.com/buildbuddy-io/buildbuddy/server/util/clickhouse"
	"github.com/buildbuddy-io/buildbuddy/server/util/clickhouse/schema"
	"github.com/buildbuddy-io/buildbuddy/server/util/testing/flags"
	"github.com/stretchr/testify/require"
	"google.golang.org/protobuf/types/known/structpb"

	expb "github.com/buildbuddy-io/buildbuddy/proto/experiments"
	repb "github.com/buildbuddy-io/buildbuddy/proto/remote_execution"
	sipb "github.com/buildbuddy-io/buildbuddy/proto/stored_invocation"
)

// TestExecutionIDRoundTripThroughClickHouseSchema verifies that an execution
// ID generated by the server via digest.NewCASResourceName().NewUploadString()
// can be reconstructed from the split columns populated on schema.Execution.
func TestExecutionIDRoundTripThroughClickHouseSchema(t *testing.T) {
	const sha256Hash = "072d9dd55aacaa829d7d1cc9ec8c4b5180ef49acac4a3c2f3ca16a3db134982d"

	for _, tc := range []struct {
		name           string
		instanceName   string
		digestFunction repb.DigestFunction_Value
		compressor     repb.Compressor_Value
		sizeBytes      int64
	}{
		{name: "OldStyleSha256", instanceName: "instance_name", digestFunction: repb.DigestFunction_SHA256, compressor: repb.Compressor_IDENTITY, sizeBytes: 1234},
		{name: "Blake3", instanceName: "instance_name", digestFunction: repb.DigestFunction_BLAKE3, compressor: repb.Compressor_IDENTITY, sizeBytes: 9876},
		{name: "Sha256Zstd", instanceName: "instance_name", digestFunction: repb.DigestFunction_SHA256, compressor: repb.Compressor_ZSTD, sizeBytes: 4321},
		{name: "Blake3Zstd", instanceName: "instance_name", digestFunction: repb.DigestFunction_BLAKE3, compressor: repb.Compressor_ZSTD, sizeBytes: 55},
		{name: "EmptyInstanceName", instanceName: "", digestFunction: repb.DigestFunction_SHA256, compressor: repb.Compressor_IDENTITY, sizeBytes: 7},
		{name: "InstanceNameContainingUploads", instanceName: "bad/uploads/instance", digestFunction: repb.DigestFunction_SHA256, compressor: repb.Compressor_IDENTITY, sizeBytes: 42},
		// DEFLATE is unsupported by URL construction/parsing, so it is treated
		// as IDENTITY: NewUploadString emits a "blobs" URL and the parser
		// recovers Compressor_IDENTITY. The round-trip still matches.
		{name: "DeflateUnsupported", instanceName: "instance_name", digestFunction: repb.DigestFunction_SHA256, compressor: repb.Compressor_DEFLATE, sizeBytes: 99},
	} {
		t.Run(tc.name, func(t *testing.T) {
			rn := digest.NewCASResourceName(
				&repb.Digest{Hash: sha256Hash, SizeBytes: tc.sizeBytes},
				tc.instanceName,
				tc.digestFunction,
			)
			rn.SetCompressor(tc.compressor)
			executionID := rn.NewUploadString()

			execution, err := clickhouse.ExecutionFromProto(&repb.StoredExecution{ExecutionId: executionID}, nil)
			require.NoError(t, err)

			require.Equal(t, executionID, reconstructExecutionID(t, execution))
		})
	}
}

func TestExecutionFromProto(t *testing.T) {
	executionID := digest.NewCASResourceName(
		&repb.Digest{
			Hash:      "072d9dd55aacaa829d7d1cc9ec8c4b5180ef49acac4a3c2f3ca16a3db134982d",
			SizeBytes: 1234,
		},
		"test-instance-name",
		repb.DigestFunction_SHA256,
	).NewUploadString()

	for _, testCase := range []struct {
		name string
		in   *repb.StoredExecution
		want *schema.Execution
	}{
		{
			name: "MinimalExecution",
			in: &repb.StoredExecution{
				ExecutionId: executionID,
			},
			want: &schema.Execution{},
		},
		{
			name: "RecycleRunner",
			in: &repb.StoredExecution{
				ExecutionId:   executionID,
				RecycleRunner: true,
			},
			want: &schema.Execution{
				RecycleRunner: true,
			},
		},
		{
			name: "VMMetrics",
			in: &repb.StoredExecution{
				ExecutionId:               executionID,
				VmDockerdWaitDurationUsec: 4001,
				VmDnsWaitDurationUsec:     4002,
				VmExecInitDurationUsec:    4003,
				VmExecDialDurationUsec:    4004,
			},
			want: &schema.Execution{
				VMDockerdWaitDurationUsec: 4001,
				VMDnsWaitDurationUsec:     4002,
				VMExecInitDurationUsec:    4003,
				VMExecDialDurationUsec:    4004,
			},
		},
		{
			name: "RequestAndTestMetadata",
			in: &repb.StoredExecution{
				ExecutionId:     executionID,
				TargetLabel:     "//some:test",
				ActionMnemonic:  "TestRunner",
				ConfigurationId: "26b4b27c1032c7df9ed4ffe75e295384222c5464200cf73616ef1beeb8f8028d",
				TestSize:        "large",
				TestShardIndex:  2,
				TestTotalShards: 6,
			},
			want: &schema.Execution{
				TargetLabel:     "//some:test",
				ActionMnemonic:  "TestRunner",
				ConfigurationID: "26b4b27c1032c7df9ed4ffe75e295384222c5464200cf73616ef1beeb8f8028d",
				TestSize:        "large",
				TestShardIndex:  2,
				TestTotalShards: 6,
			},
		},
	} {
		t.Run(testCase.name, func(t *testing.T) {
			// Convert the stored execution as the ClickHouse flush path does.
			execution, err := clickhouse.ExecutionFromProto(testCase.in, nil)
			require.NoError(t, err)

			// The row should preserve direct proto fields while also parsing
			// the execution ID resource fields.
			require.Equal(t, testCase.want.RecycleRunner, execution.RecycleRunner)
			require.Equal(t, testCase.want.TargetLabel, execution.TargetLabel)
			require.Equal(t, testCase.want.ActionMnemonic, execution.ActionMnemonic)
			require.Equal(t, testCase.want.ConfigurationID, execution.ConfigurationID)
			require.Equal(t, testCase.want.TestSize, execution.TestSize)
			require.Equal(t, testCase.want.TestShardIndex, execution.TestShardIndex)
			require.Equal(t, testCase.want.TestTotalShards, execution.TestTotalShards)
			require.Equal(t, testCase.want.VMDockerdWaitDurationUsec, execution.VMDockerdWaitDurationUsec)
			require.Equal(t, testCase.want.VMDnsWaitDurationUsec, execution.VMDnsWaitDurationUsec)
			require.Equal(t, testCase.want.VMExecInitDurationUsec, execution.VMExecInitDurationUsec)
			require.Equal(t, testCase.want.VMExecDialDurationUsec, execution.VMExecDialDurationUsec)
			require.Equal(t, testCase.in.GetExecutionId(), reconstructExecutionID(t, execution))
		})
	}
}

func reconstructExecutionID(t *testing.T, e *schema.Execution) string {
	d := &repb.Digest{
		Hash:      hex.EncodeToString([]byte(e.ActionDigestHash)),
		SizeBytes: int64(e.ActionDigestSize),
	}
	df, err := digest.DigestFunctionFromSegment(e.DigestFunction, d)
	require.NoError(t, err)
	compressor, err := digest.CompressorFromSegment(e.Compressor)
	require.NoError(t, err)
	rn := digest.NewCASResourceName(d, e.InstanceName, df)
	rn.SetCompressor(compressor)
	return rn.UploadString(e.ExecutionUUID)
}

func TestFlushExecutionStats_SkipsMalformedExecutionIDs(t *testing.T) {
	flags.Set(t, "testenv.use_clickhouse", true)
	flags.Set(t, "testenv.reuse_server", true)

	ctx := context.Background()
	env := testenv.GetTestEnv(t)

	invocationID := "6ec99c6d-5504-4934-9f31-a9b65af4ec76"
	invocationUUID := strings.ReplaceAll(invocationID, "-", "")
	invocation := &sipb.StoredInvocation{InvocationId: invocationID}
	nowUsec := time.Now().UnixMicro()

	validExecutionID := digest.NewCASResourceName(
		&repb.Digest{
			Hash:      "072d9dd55aacaa829d7d1cc9ec8c4b5180ef49acac4a3c2f3ca16a3db134982d",
			SizeBytes: 1234,
		},
		"test-instance-name",
		repb.DigestFunction_SHA256,
	).NewUploadString()

	err := env.GetOLAPDBHandle().FlushExecutionStats(ctx, invocation, []*repb.StoredExecution{
		{
			ExecutionId:     validExecutionID,
			InvocationUuid:  invocationUUID,
			UpdatedAtUsec:   nowUsec,
			CreatedAtUsec:   nowUsec,
			ConfigurationId: "26b4b27c1032c7df9ed4ffe75e295384222c5464200cf73616ef1beeb8f8028d",
			TestSize:        "enormous",
			TestShardIndex:  3,
			TestTotalShards: 8,
		},
		{
			ExecutionId:    "not-a-resource-name",
			InvocationUuid: invocationUUID,
			UpdatedAtUsec:  nowUsec,
			CreatedAtUsec:  nowUsec,
		},
		{
			// Empty execution ID is also rejected.
			ExecutionId:    "",
			InvocationUuid: invocationUUID,
			UpdatedAtUsec:  nowUsec,
			CreatedAtUsec:  nowUsec,
		},
	})
	require.NoError(t, err)

	var rows []schema.Execution
	err = env.GetOLAPDBHandle().GORM(ctx, "test_query_executions").Where(
		"invocation_uuid = ?", invocationUUID,
	).Find(&rows).Error
	require.NoError(t, err)
	require.Len(t, rows, 1)
	require.Equal(t, validExecutionID, reconstructExecutionID(t, &rows[0]))
	require.Equal(t, "26b4b27c1032c7df9ed4ffe75e295384222c5464200cf73616ef1beeb8f8028d", rows[0].ConfigurationID)
	require.Equal(t, "enormous", rows[0].TestSize)
	require.Equal(t, uint32(3), rows[0].TestShardIndex)
	require.Equal(t, uint32(8), rows[0].TestTotalShards)
}

func TestFlushExecutionStats_AllMalformedExecutionIDs_SkipsInsert(t *testing.T) {
	flags.Set(t, "testenv.use_clickhouse", true)
	flags.Set(t, "testenv.reuse_server", true)

	ctx := context.Background()
	env := testenv.GetTestEnv(t)

	invocationID := "7118a8ef-f598-4e83-9953-a3b4b799d3ab"
	invocationUUID := strings.ReplaceAll(invocationID, "-", "")
	invocation := &sipb.StoredInvocation{InvocationId: invocationID}
	nowUsec := time.Now().UnixMicro()

	err := env.GetOLAPDBHandle().FlushExecutionStats(ctx, invocation, []*repb.StoredExecution{
		{
			ExecutionId:    "bad-1",
			InvocationUuid: invocationUUID,
			UpdatedAtUsec:  nowUsec,
			CreatedAtUsec:  nowUsec,
		},
		{
			ExecutionId:    "bad-2",
			InvocationUuid: invocationUUID,
			UpdatedAtUsec:  nowUsec,
			CreatedAtUsec:  nowUsec,
		},
	})
	require.NoError(t, err)

	var count int64
	err = env.GetOLAPDBHandle().GORM(ctx, "test_count_executions").Model(&schema.Execution{}).Where(
		"invocation_uuid = ?", invocationUUID,
	).Count(&count).Error
	require.NoError(t, err)
	require.Zero(t, count)
}

func TestFlushExecutionStats_ExperimentFlags(t *testing.T) {
	flags.Set(t, "testenv.use_clickhouse", true)
	flags.Set(t, "testenv.reuse_server", true)
	env := testenv.GetTestEnv(t)
	ctx := t.Context()

	object, err := structpb.NewStruct(map[string]any{
		"z":   nil,
		"a.b": map[string]any{"z": false, "a": map[string]any{}},
	})
	require.NoError(t, err)
	experimentFlags := []*expb.EvaluatedFlag{
		{Name: "executor.string", Value: &expb.EvaluatedFlag_StringValue{StringValue: ""}},
		{Name: "executor.object", Variant: "nested", Value: &expb.EvaluatedFlag_ObjectValue{ObjectValue: object}},
		{Name: "executor.int64", Value: &expb.EvaluatedFlag_Int64Value{Int64Value: 9007199254740993}},
		{Name: "executor.float64", Value: &expb.EvaluatedFlag_Float64Value{Float64Value: 1}},
		{Name: "executor.bool", Variant: "control", Value: &expb.EvaluatedFlag_BoolValue{BoolValue: false}},
		{Name: "executor.zero", Value: &expb.EvaluatedFlag_Int64Value{Int64Value: 0}},
		{Name: "executor.empty_object", Value: &expb.EvaluatedFlag_ObjectValue{ObjectValue: &structpb.Struct{}}},
	}
	const invocationID = "f613dc0a-c1c4-40c9-8193-cbf428c5d321"
	invocation := &sipb.StoredInvocation{InvocationId: invocationID}
	invocationUUID := strings.ReplaceAll(invocationID, "-", "")
	var executions []*repb.StoredExecution
	for _, values := range [][]*expb.EvaluatedFlag{nil, experimentFlags} {
		executionID := digest.NewCASResourceName(&repb.Digest{
			Hash: strings.Repeat("a", 64), SizeBytes: 123,
		}, "", repb.DigestFunction_SHA256).NewUploadString()
		executions = append(executions, &repb.StoredExecution{
			ExecutionId: executionID, InvocationUuid: invocationUUID,
			UpdatedAtUsec: time.Now().UnixMicro(), ExperimentFlags: values,
		})
	}

	require.NoError(t, env.GetOLAPDBHandle().FlushExecutionStats(ctx, invocation, executions))

	var storedKeys []string
	err = env.GetOLAPDBHandle().GORM(ctx, "test_experiment_keys").Raw(`
		SELECT mapKeys(experiment_flags) AS names
		FROM Executions
		WHERE invocation_uuid = ? AND notEmpty(experiment_flags)
	`, invocationUUID).Row().Scan(&storedKeys)
	require.NoError(t, err)
	require.Equal(t, []string{
		"executor.bool", "executor.empty_object", "executor.float64", "executor.int64",
		"executor.object", "executor.string", "executor.zero",
	}, storedKeys)

	type evaluation struct {
		Name            string
		Variant         string
		BoolValue       *bool
		StringValue     *string
		Int64Value      *int64
		Float64Value    *float64
		ObjectValueJSON *string
	}
	var got []evaluation
	err = env.GetOLAPDBHandle().GORM(ctx, "test_experiment_values").Raw(`
		SELECT
			name,
			getSubcolumn(experiment_flags[name], 'variant') AS variant,
			getSubcolumn(experiment_flags[name], 'bool_value') AS bool_value,
			getSubcolumn(experiment_flags[name], 'string_value') AS string_value,
			getSubcolumn(experiment_flags[name], 'int64_value') AS int64_value,
			getSubcolumn(experiment_flags[name], 'float64_value') AS float64_value,
			getSubcolumn(experiment_flags[name], 'object_value_json') AS object_value_json
		FROM Executions
		ARRAY JOIN mapKeys(experiment_flags) AS name
		WHERE invocation_uuid = ?
		ORDER BY name
	`, invocationUUID).Scan(&got).Error
	require.NoError(t, err)
	require.Equal(t, []evaluation{
		{Name: "executor.bool", Variant: "control", BoolValue: new(false)},
		{Name: "executor.empty_object", ObjectValueJSON: new("{}")},
		{Name: "executor.float64", Float64Value: new(float64(1))},
		{Name: "executor.int64", Int64Value: new(int64(9007199254740993))},
		{Name: "executor.object", Variant: "nested", ObjectValueJSON: new(`{"a.b":{"a":{},"z":false},"z":null}`)},
		{Name: "executor.string", StringValue: new("")},
		{Name: "executor.zero", Int64Value: new(int64(0))},
	}, got)

	var rows []schema.Execution
	err = env.GetOLAPDBHandle().GORM(ctx, "test_experiment_rows").Where("invocation_uuid = ?", invocationUUID).Find(&rows).Error
	require.NoError(t, err)
	require.Len(t, rows, 2)
	lengths := []int{len(rows[0].ExperimentFlags), len(rows[1].ExperimentFlags)}
	slices.Sort(lengths)
	require.Equal(t, []int{0, len(experimentFlags)}, lengths)
}

func TestFlushExecutionStats_WithoutExperimentFlagsColumn(t *testing.T) {
	flags.Set(t, "testenv.use_clickhouse", true)
	flags.Set(t, "testenv.reuse_server", true)
	env := testenv.GetTestEnv(t)
	ctx := t.Context()

	// Simulate a ClickHouse server that is too old for the JSON type, where
	// migrations leave out the experiment_flags column. Then connect again
	// without migrations, so that the new handle sees the table without it.
	err := env.GetOLAPDBHandle().GORM(ctx, "test_drop_experiment_flags").Exec(
		"ALTER TABLE Executions DROP COLUMN experiment_flags",
	).Error
	require.NoError(t, err)
	flags.Set(t, "olap_database.auto_migrate_db", false)
	err = clickhouse.Register(env)
	require.NoError(t, err)

	// Flush an execution that reports an experiment flag.
	const invocationID = "0b5f1c9e-7a3d-4c2b-9e8f-1d2c3b4a5f6e"
	invocation := &sipb.StoredInvocation{InvocationId: invocationID}
	invocationUUID := strings.ReplaceAll(invocationID, "-", "")
	executionID := digest.NewCASResourceName(&repb.Digest{
		Hash: strings.Repeat("a", 64), SizeBytes: 123,
	}, "", repb.DigestFunction_SHA256).NewUploadString()
	executions := []*repb.StoredExecution{{
		ExecutionId: executionID, InvocationUuid: invocationUUID,
		UpdatedAtUsec: time.Now().UnixMicro(),
		ExperimentFlags: []*expb.EvaluatedFlag{
			{Name: "executor.bool", Variant: "treatment", Value: &expb.EvaluatedFlag_BoolValue{BoolValue: true}},
		},
	}}
	err = env.GetOLAPDBHandle().FlushExecutionStats(ctx, invocation, executions)
	require.NoError(t, err)

	// The execution should be stored without its experiment flags.
	var count int64
	err = env.GetOLAPDBHandle().GORM(ctx, "test_count_executions").Model(&schema.Execution{}).Where(
		"invocation_uuid = ?", invocationUUID,
	).Count(&count).Error
	require.NoError(t, err)
	require.Equal(t, int64(1), count)
}
