package clickhouse_test

import (
	"encoding/hex"
	"strconv"
	"strings"
	"testing"

	"github.com/buildbuddy-io/buildbuddy/server/remote_cache/digest"
	"github.com/buildbuddy-io/buildbuddy/server/util/clickhouse"
	"github.com/buildbuddy-io/buildbuddy/server/util/clickhouse/schema"
	"github.com/stretchr/testify/require"

	repb "github.com/buildbuddy-io/buildbuddy/proto/remote_execution"
)

func TestExecutionFromProtoPopulatesExecutionResourceFields(t *testing.T) {
	const uploadID = "2148e1f1-aacc-41eb-a31c-22b6da7c7ac1"
	const sha256Hash = "072d9dd55aacaa829d7d1cc9ec8c4b5180ef49acac4a3c2f3ca16a3db134982d"

	for _, tc := range []struct {
		name             string
		executionID      string
		instanceName     string
		executionUUID    string
		compressor       string
		digestFunction   string
		digestHash       string
		actionDigestSize uint32
	}{
		{
			name:             "OldStyleSha256",
			executionID:      "instance_name/uploads/" + uploadID + "/blobs/" + sha256Hash + "/1234",
			instanceName:     "instance_name",
			executionUUID:    uploadID,
			compressor:       "",
			digestFunction:   "",
			digestHash:       sha256Hash,
			actionDigestSize: 1234,
		},
		{
			name:             "ExplicitDigestFunctionAndCompression",
			executionID:      "instance_name/uploads/" + uploadID + "/compressed-blobs/zstd/sha256/" + sha256Hash + "/9876",
			instanceName:     "instance_name",
			executionUUID:    uploadID,
			compressor:       "zstd",
			digestFunction:   "sha256",
			digestHash:       sha256Hash,
			actionDigestSize: 9876,
		},
		{
			name:             "InstanceNameContainingUploads",
			executionID:      "bad/uploads/instance/uploads/" + uploadID + "/blobs/" + sha256Hash + "/4321",
			instanceName:     "bad/uploads/instance",
			executionUUID:    uploadID,
			compressor:       "",
			digestFunction:   "",
			digestHash:       sha256Hash,
			actionDigestSize: 4321,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			execution, err := clickhouse.ExecutionFromProto(&repb.StoredExecution{ExecutionId: tc.executionID}, nil)
			require.NoError(t, err)

			expectedDigest, err := hex.DecodeString(tc.digestHash)
			require.NoError(t, err)

			require.Equal(t, tc.instanceName, execution.InstanceName)
			require.Equal(t, tc.executionUUID, execution.ExecutionUUID)
			require.Equal(t, tc.compressor, execution.Compressor)
			require.Equal(t, tc.digestFunction, execution.DigestFunction)
			require.Equal(t, string(expectedDigest), execution.ActionDigest)
			require.Equal(t, tc.actionDigestSize, execution.ActionDigestSize)
		})
	}
}

// TestExecutionIDRoundTripThroughClickHouseSchema verifies that an execution
// ID generated by the server via digest.NewCASResourceName().NewUploadString()
// can be reconstructed from the split columns populated on schema.Execution.
func TestExecutionIDRoundTripThroughClickHouseSchema(t *testing.T) {
	const sha256Hash = "072d9dd55aacaa829d7d1cc9ec8c4b5180ef49acac4a3c2f3ca16a3db134982d"

	for _, tc := range []struct {
		name           string
		instanceName   string
		digestFunction repb.DigestFunction_Value
		compressor     repb.Compressor_Value
		sizeBytes      int64
	}{
		{name: "OldStyleSha256", instanceName: "instance_name", digestFunction: repb.DigestFunction_SHA256, compressor: repb.Compressor_IDENTITY, sizeBytes: 1234},
		{name: "Blake3", instanceName: "instance_name", digestFunction: repb.DigestFunction_BLAKE3, compressor: repb.Compressor_IDENTITY, sizeBytes: 9876},
		{name: "Sha256Zstd", instanceName: "instance_name", digestFunction: repb.DigestFunction_SHA256, compressor: repb.Compressor_ZSTD, sizeBytes: 4321},
		{name: "Blake3Zstd", instanceName: "instance_name", digestFunction: repb.DigestFunction_BLAKE3, compressor: repb.Compressor_ZSTD, sizeBytes: 55},
		{name: "EmptyInstanceName", instanceName: "", digestFunction: repb.DigestFunction_SHA256, compressor: repb.Compressor_IDENTITY, sizeBytes: 7},
		{name: "InstanceNameContainingUploads", instanceName: "bad/uploads/instance", digestFunction: repb.DigestFunction_SHA256, compressor: repb.Compressor_IDENTITY, sizeBytes: 42},
	} {
		t.Run(tc.name, func(t *testing.T) {
			rn := digest.NewCASResourceName(
				&repb.Digest{Hash: sha256Hash, SizeBytes: tc.sizeBytes},
				tc.instanceName,
				tc.digestFunction,
			)
			rn.SetCompressor(tc.compressor)
			executionID := rn.NewUploadString()

			execution, err := clickhouse.ExecutionFromProto(&repb.StoredExecution{ExecutionId: executionID}, nil)
			require.NoError(t, err)

			require.Equal(t, executionID, reconstructExecutionID(execution))
		})
	}
}

// reconstructExecutionID rebuilds the execution ID from the split columns
// populated on schema.Execution. Intended to match the exact string produced
// by (*digest.CASResourceName).NewUploadString.
func reconstructExecutionID(e *schema.Execution) string {
	blobType := "blobs"
	if e.Compressor != "" {
		blobType = "compressed-blobs/" + e.Compressor
	}
	id := strings.Join([]string{e.InstanceName, "uploads", e.ExecutionUUID, blobType}, "/")
	if e.DigestFunction != "" {
		id += "/" + e.DigestFunction
	}
	id += "/" + hex.EncodeToString([]byte(e.ActionDigest))
	id += "/" + strconv.FormatUint(uint64(e.ActionDigestSize), 10)
	return id
}
