load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "internal",
    srcs = ["internal.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/lookuplist/internal",
    visibility = ["//server/util/lookuplist:__subpackages__"],
)
