load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//enterprise:__subpackages__"])

go_library(
    name = "mocksaml",
    srcs = ["mocksaml.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/enterprise/server/util/mocksaml",
    visibility = ["//visibility:public"],
)
