load("//rules/typescript:index.bzl", "ts_library")

ts_library(
    name = "terminal",
    srcs = ["terminal.tsx"],
    deps = [
        "//website/src/components/terminal:terminal.module.css",
        "@npm//@types/react",
        "@npm//react",
        "@npm//tslib",
    ],
)
