load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "performance",
    srcs = ["performance.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/codesearch/performance",
    visibility = ["//visibility:public"],
    deps = ["//server/util/log"],
)
