load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//enterprise:__subpackages__"])

go_library(
    name = "webhook_data",
    srcs = ["webhook_data.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/enterprise/server/webhooks/webhook_data",
)
