load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "flags",
    srcs = ["flags.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/testing/flags",
    visibility = ["//visibility:public"],
)
