load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "clientip",
    srcs = ["clientip.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/clientip",
    visibility = ["//visibility:public"],
)
