load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "ioutil",
    srcs = ["ioutil.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/ioutil",
    visibility = ["//visibility:public"],
    deps = ["//server/interfaces"],
)
