allowBuilds:
  protobufjs: true

"packageExtensions":
  "react-slider":
    # Fixes an issue that esbuild can't build react-slider because it implicitly depends on @babel/runtime.
    "dependencies":
      "@babel/runtime": "7.26.10"
