load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//cli:__subpackages__"])

go_library(
    name = "cli_command",
    srcs = ["cli_command.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/cli/cli_command",
)
