sh_test(
    name = "test_disk",
    srcs = ["test_disk.sh"],
    tags = [
        "manual",
        "no-sandbox",
    ],
)

sh_test(
    name = "test_memory",
    srcs = ["test_memory.sh"],
    tags = [
        "manual",
        "no-sandbox",
    ],
)
