load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "hash",
    srcs = ["hash.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/hash",
    visibility = ["//visibility:public"],
)
