load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "gatewayauth",
    srcs = ["gatewayauth.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/enterprise/gateway/gatewayauth",
)
