load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "dnstypes",
    srcs = ["dnstypes.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/networking/dnstypes",
    visibility = ["//visibility:public"],
)
