load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "placement",
    srcs = ["placement.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/enterprise/server/raft/placement",
    visibility = ["//visibility:public"],
)
