load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "httpcounter",
    testonly = 1,
    srcs = ["httpcounter.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/testutil/httpcounter",
    visibility = ["//visibility:public"],
)
