load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "id",
    srcs = ["id.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/id",
    visibility = ["//visibility:public"],
)
