load("//rules/typescript:index.bzl", "ts_library")

ts_library(
    name = "index",
    srcs = ["index.tsx"],
    deps = [
        "//website/theme:BlogPostItem",
        "//website/theme:BlogSidebar",
        "@npm//@docusaurus/useDocusaurusContext",
        "@npm//@theme/BlogListPage",
        "@npm//@theme/BlogListPaginator",
        "@npm//@theme/Layout",
        "@npm//@types/react",
        "@npm//react",
    ],
)
