FROM mirror.gcr.io/library/alpine@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1

RUN apk add --no-cache \
    argp-standalone bash build-base json-c-dev libcap-dev libcap-static \
    libseccomp-dev libseccomp-static linux-headers pkgconf python3
