load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "usageutil",
    srcs = ["usageutil.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/usageutil",
    visibility = ["//visibility:public"],
    deps = ["//server/tables"],
)
