load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "background",
    srcs = ["background.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/background",
    visibility = ["//visibility:public"],
)
