load("//rules/typescript:index.bzl", "ts_library")

ts_library(
    name = "index",
    srcs = ["index.tsx"],
    deps = [
        "//website/theme:BlogSidebar",
        "@npm//@docusaurus/Link",
        "@npm//@docusaurus/Translate",
        "@npm//@theme/BlogTagsListPage",
        "@npm//@theme/Layout",
        "@npm//@types/react",
        "@npm//react",
    ],
)
