load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "qps",
    srcs = ["qps.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/qps",
    visibility = ["//visibility:public"],
)
