load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//cli:__subpackages__"])

go_library(
    name = "agentutil",
    srcs = ["agentutil.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/cli/util/agent/agentutil",
    visibility = ["//visibility:public"],
)
