load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "sku",
    srcs = ["sku.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/usage/sku",
    visibility = ["//visibility:public"],
)
