load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "endpoints",
    srcs = ["endpoints.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/enterprise/server/container_registry/endpoints",
    visibility = ["//visibility:public"],
)

package(default_visibility = ["//enterprise:__subpackages__"])
