load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "nsutil",
    srcs = ["nsutil.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/nsutil",
    target_compatible_with = ["@platforms//os:linux"],
    visibility = ["//visibility:public"],
)
