load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "olapdbconfig",
    srcs = ["olapdbconfig.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/olapdbconfig",
    visibility = ["//visibility:public"],
)
