load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "unixcred",
    srcs = ["unixcred.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/unixcred",
    visibility = ["//visibility:public"],
)
