sh_test(
    name = "copy_file_test",
    srcs = ["copy_file_test.sh"],
    exec_properties = {
        "EstimatedComputeUnits": "1",
    },
)

sh_test(
    name = "burn_cpu_test",
    srcs = ["burn_cpu_test.sh"],
    exec_properties = {
        "EstimatedComputeUnits": "1",
    },
)
