load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["lru.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/lru",
    visibility = ["//visibility:public"],
)
