// Package fix implements the `bb fix` command, which tidies up a Bazel
// workspace so it builds. It extends gazelle and buildifier with extra
// fix-ups, and will synthesize a minimal Bazel workspace (an empty
// MODULE.bazel) when run in a repo that doesn't have one yet, so the same
// command can bootstrap a new project or maintain an existing one.
//
// Concretely, it walks the repo to:
//   - run buildifier on BUILD, WORKSPACE, MODULE.bazel, and .bzl files
//     (translating non-Bazel build files first when possible);
//   - detect languages in use (e.g. Go, TypeScript) from source and dep files
//     such as go.mod or package.json;
//   - add the corresponding rules to MODULE.bazel/WORKSPACE via `bb add`; and
//   - import third-party deps: under WORKSPACE, by running
//     `gazelle update-repos` into a deps.bzl macro; under bzlmod, via
//     language-specific module extension wiring (e.g. go_deps.from_file).
//
// Finally it runs Gazelle to generate/update BUILD files, preferring a
// repo-defined //:gazelle target (required for bzlmod) and falling back to the
// built-in Gazelle otherwise.
//
// The --diff flag previews buildifier and Gazelle changes without writing
// them; other fixes (dep additions, update-repos) are skipped in diff mode.
//
// `bb fix` exits non-zero if buildifier or Gazelle fails (e.g. a BUILD file
// doesn't parse), and with --diff, also if there are changes to apply. It
// still runs Gazelle after a buildifier failure, and reports all failures at
// the end.
package fix

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/bazel-contrib/buildtools/v10/edit"
	"github.com/buildbuddy-io/buildbuddy/cli/add"
	"github.com/buildbuddy-io/buildbuddy/cli/arg"
	"github.com/buildbuddy-io/buildbuddy/cli/bazelisk"
	"github.com/buildbuddy-io/buildbuddy/cli/fix/language"
	"github.com/buildbuddy-io/buildbuddy/cli/log"
	"github.com/buildbuddy-io/buildbuddy/cli/translate"
	"github.com/buildbuddy-io/buildbuddy/cli/workspace"
	"github.com/buildbuddy-io/buildbuddy/server/util/flag"

	gazelleUpdate "github.com/bazel-contrib/bazel-gazelle/v2/cmd/gazelle/update"
	buildifier "github.com/bazel-contrib/buildtools/v10/buildifier"
	gazelle "github.com/bazelbuild/bazel-gazelle/cmd/gazelle"
)

var (
	flags = flag.NewFlagSet("fix", flag.ContinueOnError)
	Flags = flags
	diff  = flags.Bool("diff", false, "Don't apply fixes, just print a diff showing the changes that would be applied.")
)

const (
	usage = `
usage: bb fix [ --diff ]

Applies fixes to WORKSPACE and BUILD files.
Use the --diff flag to print suggested fixes without applying.
`
	gazelleTarget = "//:gazelle"
)

var nonAlphanumericRegex = regexp.MustCompile(`[^a-zA-Z0-9 ]+`)

// errDiff is returned in --diff mode by steps that found changes to apply.
var errDiff = errors.New("found changes to apply; run `bb fix` without --diff to apply them")

func HandleFix(args []string) (exitCode int, err error) {
	if err := arg.ParseFlagSet(flags, args); err != nil {
		if err == flag.ErrHelp {
			log.Print(usage)
			flags.SetOutput(os.Stderr)
			flags.PrintDefaults()
			return 1, nil
		}
		return -1, err
	}

	path, baseFile, err := workspace.CreateModuleIfNotExists()
	if err != nil {
		return 1, err
	}

	// Run Gazelle even if the walk failed, so that one bad file doesn't stop
	// everything else from being fixed.
	walkErr := walk(baseFile)
	gazelleErr := runGazelle(path, baseFile)
	if err := joinErrors([]error{walkErr, gazelleErr}); err != nil {
		return 1, err
	}
	return 0, nil
}

func runGazelle(repoRoot, baseFile string) error {
	// With MODULE.bazel, Gazelle needs access to a config file generated by a
	// repo rule managed by the gazelle module. We thus prefer to run Gazelle
	// from the repo if available, falling back to the built-in Gazelle
	// otherwise.
	opts := edit.NewOpts()
	opts.OutWriter = io.Discard
	opts.ErrWriter = io.Discard
	exitCode := edit.Buildozer(opts, []string{"print name", gazelleTarget})
	if exitCode == 0 {
		return runRepoGazelle()
	} else {
		return runBuiltinGazelle(repoRoot, baseFile)
	}
}

func runRepoGazelle() error {
	log.Debugf("Running %s", gazelleTarget)
	args := []string{"run", "--", gazelleTarget}
	if *diff {
		args = append(args, "-mode=diff")
	}
	exitCode, err := bazelisk.Run(args, &bazelisk.RunOpts{})
	if err != nil {
		return fmt.Errorf("run %s: %w", gazelleTarget, err)
	}
	if exitCode != 0 {
		// In diff mode, Gazelle exits 1 both for diffs and for errors.
		return fmt.Errorf("`bazel run %s` exited with code %d", gazelleTarget, exitCode)
	}
	return nil
}

func runBuiltinGazelle(repoRoot, baseFile string) error {
	originalArgs := os.Args
	defer func() {
		os.Args = originalArgs
	}()

	os.Args = []string{"gazelle", "update"}
	if baseFile == workspace.ModuleFileName {
		os.Args = append(os.Args, "-bzlmod", "-repo_root="+repoRoot)
	} else {
		os.Args = append(os.Args, "-repo_root="+repoRoot, "-go_prefix=")
	}

	if *diff {
		os.Args = append(os.Args, "-mode=diff")
	}
	log.Debugf("Calling gazelle with args: %+v", os.Args)
	return gazelleError(gazelle.Run())
}

// gazelleError converts an error from the embedded Gazelle into one to report.
func gazelleError(err error) error {
	if errors.Is(err, gazelleUpdate.ErrDiff) {
		return errDiff
	}
	if err != nil {
		return fmt.Errorf("gazelle: %w", err)
	}
	return nil
}

// walk formats build files and, outside of --diff mode, adds and registers the
// dependencies of the languages used in the repo. It returns all the errors it
// encountered.
func walk(moduleOrWorkspaceFile string) error {
	var errs []error
	languages := getLanguages()
	foundLanguages := map[language.Language]bool{}
	depFiles := map[string][]string{}
	err := filepath.WalkDir(".",
		func(path string, d os.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() {
				// Don't recurse into hidden directories such as .git or .ijwb
				// (IntelliJ).
				if d.Name() != "." && strings.HasPrefix(d.Name(), ".") {
					return filepath.SkipDir
				} else {
					return nil
				}
			}
			// .bzl files are formatted directly by buildifier.
			if strings.HasSuffix(path, ".bzl") {
				errs = append(errs, runBuildifier(path))
				return nil
			}

			fileName := filepath.Base(path)
			// Collect any languages and their dep files we found used in the repo.
			for _, l := range languages {
				if l.IsSourceFile(path) {
					foundLanguages[l] = true
				}
				if !l.IsDepFile(path) {
					continue
				}
				foundLanguages[l] = true
				if _, ok := depFiles[fileName]; !ok {
					depFiles[fileName] = []string{}
				}
				depFiles[fileName] = append(depFiles[fileName], path)
			}
			fileNameRoot := strings.TrimSuffix(fileName, filepath.Ext(fileName))
			if fileNameRoot != "BUILD" && fileNameRoot != "WORKSPACE" && fileNameRoot != "MODULE" {
				return nil
			}
			fileToFormat, err := translate.Translate(path)
			if err != nil {
				return err
			}
			if fileToFormat == "" {
				return nil
			}
			errs = append(errs, runBuildifier(fileToFormat))
			return nil
		})
	if err != nil {
		errs = append(errs, err)
		return joinErrors(errs)
	}

	if *diff {
		// TODO: support diff mode for other fixes
		return joinErrors(errs)
	}

	// Add any necessary dependencies for languages that are used in the repo.
	for l := range foundLanguages {
		for _, d := range l.Deps() {
			log.Debugf("Adding %s", d)
			_, err := add.HandleAdd([]string{d})
			if err != nil {
				log.Debugf("Failed adding %s: %s", d, err)
			}
		}
		depFiles = l.ConsolidateDepFiles(depFiles)
	}

	// Run update-repos on any dependency files we found.
	for _, paths := range depFiles {
		for _, path := range paths {
			errs = append(errs, runUpdateRepos(path, moduleOrWorkspaceFile))
			for l := range foundLanguages {
				if l.IsDepFile(path) {
					l.RegisterDeps(path, moduleOrWorkspaceFile)
				}
			}
		}
	}

	return joinErrors(errs)
}

// joinErrors is errors.Join, except that errDiff appears at most once.
func joinErrors(errs []error) error {
	var out []error
	sawDiff := false
	for _, err := range flatten(errs) {
		if err == errDiff {
			if sawDiff {
				continue
			}
			sawDiff = true
		}
		out = append(out, err)
	}
	return errors.Join(out...)
}

// flatten expands errors created by errors.Join into their parts.
func flatten(errs []error) []error {
	var out []error
	for _, err := range errs {
		if joined, ok := err.(interface{ Unwrap() []error }); ok {
			out = append(out, flatten(joined.Unwrap())...)
		} else if err != nil {
			out = append(out, err)
		}
	}
	return out
}

// Collect the languages that support auto-generating WORKSPACE files.
func getLanguages() []language.Language {
	var languages []language.Language
	for _, l := range gazelle.Languages {
		if l, ok := l.(language.Language); ok {
			languages = append(languages, l)
		}
	}
	return languages
}

// runBuildifier formats (or with --diff, diffs) the given file.
func runBuildifier(path string) error {
	originalArgs := os.Args
	defer func() {
		os.Args = originalArgs
	}()
	os.Args = []string{"buildifier"}
	if *diff {
		os.Args = append(
			os.Args,
			"-mode=diff",
			// Pass -u arg to diff for slightly nicer output.
			"-diff_command=diff -u",
		)
	}
	os.Args = append(os.Args, path)
	switch exitCode := buildifier.Run(); {
	case exitCode == 0:
		return nil
	case exitCode == 4 && *diff:
		// Exit code 4 means the file needs reformatting.
		return errDiff
	default:
		return fmt.Errorf("buildifier %s: exit code %d", path, exitCode)
	}
}

func runUpdateRepos(path string, moduleOrWorkspaceFile string) error {
	// Don't run update-repos on MODULE.bazel files.
	if moduleOrWorkspaceFile == workspace.ModuleFileName {
		return nil
	}

	originalArgs := os.Args
	defer func() {
		os.Args = originalArgs
	}()
	os.Args = []string{"gazelle", "update-repos", "-prune", "--from_file=" + path, fmt.Sprintf("--to_macro=deps.bzl%%install_%s_dependencies", nonAlphanumericRegex.ReplaceAllString(path, "_"))}
	log.Debugf("Calling gazelle with args: %+v", os.Args)
	return gazelleError(gazelle.Run())
}
