load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "cachelog",
    srcs = ["cachelog.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/cachelog",
    visibility = ["//visibility:public"],
    deps = ["//server/util/log"],
)
