load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "cookie",
    srcs = ["cookie.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/cookie",
    visibility = ["//visibility:public"],
    deps = ["//server/endpoint_urls/build_buddy_url"],
)
