apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prom
    isDefault: true
    url: http://prometheus-global-server.monitor-%{ENV}
    version: 1
    editable: false
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    uid: vm
    isDefault: false # TODO: make VM the default
    # TODO: use global cluster
    url: http://victoria-metrics-cluster-global-vmselect.monitor-%{ENV}:8481/select/0/prometheus
    version: 1
    editable: false
