apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    uid: vm
    isDefault: false # TODO: make VM the default
    # TODO: use global cluster
    url: http://victoria-metrics-cluster-global-vmselect.monitor-%{ENV}:8481/select/0/prometheus
    version: 1
    editable: false
  - name: ClickHouse (main)
    type: grafana-clickhouse-datasource
    uid: clickhouse
    jsonData:
      port: 9000
      host: clickhouse-repl-%{ENV}.clickhouse-operator-%{ENV}.svc.cluster.local
      username: buildbuddy_%{ENV}_readonly
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
  - name: ClickHouse (OTEL)
    type: grafana-clickhouse-datasource
    uid: clickhouse-otel
    jsonData:
      port: 9000
      host: clickhouse-clickhouse-otel.monitor-%{ENV}.svc.cluster.local
      username: buildbuddy_%{ENV}_readonly
      traces:
        defaultDatabase: otel_%{ENV}
        defaultTable: otel_traces
        otelEnabled: true
        otelVersion: latest # TODO: pin?
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
