# gazelle:default_visibility //cli:__subpackages__
package(default_visibility = ["//cli:__subpackages__"])

alias(
    name = "cli",
    actual = "//cli/cmd/bb",
)

exports_files(
    srcs = ["install.sh"],
)
