load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "devnull",
    srcs = ["devnull.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/devnull",
    visibility = ["//visibility:public"],
)
