load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "eventlog",
    srcs = ["eventlog.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/eventlog",
    visibility = ["//visibility:public"],
    deps = [],
)
