load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "cache_api_url",
    srcs = ["cache_api_url.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/endpoint_urls/cache_api_url",
    visibility = ["//visibility:public"],
    deps = ["//server/util/flagutil/types"],
)
