load("//rules/typescript:index.bzl", "ts_library")

ts_library(
    name = "rbe",
    srcs = ["rbe.tsx"],
    deps = [
        "//website/src/components/rbe:rbe.module.css",
        "//website/src/css:common.module.css",
        "@npm//@types/react",
        "@npm//lucide-react",
        "@npm//react",
    ],
)
