load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "file",
    srcs = ["file.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/file",
    visibility = ["//visibility:public"],
    deps = ["//server/util/status"],
)
