load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "query_builder",
    srcs = ["query_builder.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/query_builder",
    visibility = ["//visibility:public"],
)
