# Instruct Gazelle to generate go_web_test_suite rules for newly added tests,
# and let it manage deps for existing go_web_test_suite rules.

# gazelle:map_kind go_test go_web_test_suite //rules/webdriver:index.bzl
