load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "autoclose",
    srcs = ["autoclose.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/autoclose",
    visibility = ["//visibility:public"],
)
