load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "network",
    srcs = ["network.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/network",
    visibility = ["//visibility:public"],
)
