{
 "title": "Baremetal Power",
 "tags": [ "file:baremetal-power.json" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "pdu",
    "label": "PDU",
    "query": {
     "query": "label_values(pdu_snmp_scrape_pdus_returned,pdu)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total input power by rack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (pdu) (\n    pdu_infeedPower{job=\"snmp_servertech_sentry3\"}\n        or\n    pdu_st4InputCordActivePower{job=\"snmp_servertech_sentry4\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Rack ${pdu}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "pdu" },
  {
   "title": "${pdu} > Total input power by unit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (pdu, towerIndex) (pdu_infeedPower{job=\"snmp_servertech_sentry3\", pdu=\"${pdu}\"})",
     "legendFormat": "{{pdu}} > Unit {{towerIndex}}"
    },
    {
     "expr": "sum by (pdu, st4UnitName) (pdu_st4InputCordActivePower{job=\"snmp_servertech_sentry4\", pdu=\"${pdu}\"})",
     "legendFormat": "{{pdu}} > Unit {{st4UnitName}}"
    }
   ]
  },
  {
   "title": "${pdu} > Output power (POPS PDUs only)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (pdu, towerIndex, outletIndex) (pdu_outletPower{job=\"snmp_servertech_sentry3\", pdu=\"${pdu}\"})",
     "legendFormat": "{{pdu}} > Unit {{towerIndex}} > Outlet {{outletIndex}}"
    }
   ]
  }
 ]
}