{
 "title": "Baremetal Networking",
 "tags": [ "file:baremetal-networking.json" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "region",
    "query": {
     "query": "label_values(interfaces_interface_state_counters_in_octets,region)"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(interfaces_interface_state_counters_in_octets,source)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "External Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(interfaces_interface_state_counters_in_octets{region=\"${region}\", source=~\"sjc-s1|sjc-s2\", interface_name=~\"Ethernet1/1|Ethernet31/1\"}[1m])) * 8",
     "legendFormat": "ingress"
    },
    {
     "expr": "sum(rate(interfaces_interface_state_counters_out_octets{region=\"${region}\", source=~\"sjc-s1|sjc-s2\", interface_name=~\"Ethernet1/1|Ethernet31/1\"}[1m])) * 8",
     "legendFormat": "egress"
    }
   ]
  },
  {
   "title": "Traffic by device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(interfaces_interface_state_counters_in_octets{region=\"${region}\", interface_name!~\"Port-Channel.*\"}[1m])) by (source) * 8",
     "legendFormat": "ingress {{source}}"
    },
    {
     "expr": "sum(rate(interfaces_interface_state_counters_out_octets{region=\"${region}\", interface_name!~\"Port-Channel.*\"}[1m])) by (source) * 8",
     "legendFormat": "egress {{source}}"
    }
   ]
  },
  {
   "title": "Errors and Discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(interfaces_interface_state_counters_in_errors{region=\"${region}\"}[1m])) by (source)",
     "legendFormat": "ingress errors {{source}}"
    },
    {
     "expr": "sum(rate(interfaces_interface_state_counters_in_discards{region=\"${region}\"}[1m])) by (source)",
     "legendFormat": "ingress discards {{source}}"
    },
    {
     "expr": "sum(rate(interfaces_interface_state_counters_out_errors{region=\"${region}\"}[1m])) by (source)",
     "legendFormat": "egress errors {{source}}"
    },
    {
     "expr": "sum(rate(interfaces_interface_state_counters_out_discards{region=\"${region}\"}[1m])) by (source)",
     "legendFormat": "egress discards {{source}}"
    },
    {
     "expr": "sum(rate(interfaces_interface_state_counters_in_fcs_errors{region=\"${region}\"}[1m])) by (source)",
     "legendFormat": "ingress fcs errors {{source}}"
    },
    {
     "expr": "sum(rate(interfaces_interface_state_counters_out_fcs_errors{region=\"${region}\"}[1m])) by (source)",
     "legendFormat": "egress fcs errors {{source}}"
    }
   ]
  },
  {
   "title": "Device ${device}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "repeat": "device",
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic by interface",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(rate(interfaces_interface_state_counters_in_octets{region=\"${region}\", source=\"${device}\"}[1m])) by (interface_name) * 8",
       "legendFormat": "ingress {{interface_name}}"
      },
      {
       "expr": "sum(rate(interfaces_interface_state_counters_out_octets{region=\"${region}\", source=\"${device}\"}[1m])) by (interface_name) * 8",
       "legendFormat": "egress {{interface_name}}"
      }
     ]
    },
    {
     "title": "Errors and Discards by interface",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "sum(rate(interfaces_interface_state_counters_in_errors{region=\"${region}\", source=\"${device}\"}[1m])) by (interface_name)",
       "legendFormat": "ingress errors {{interface_name}}"
      },
      {
       "expr": "sum(rate(interfaces_interface_state_counters_in_discards{region=\"${region}\", source=\"${device}\"}[1m])) by (interface_name)",
       "legendFormat": "ingress discards {{interface_name}}"
      },
      {
       "expr": "sum(rate(interfaces_interface_state_counters_out_errors{region=\"${region}\", source=\"${device}\"}[1m])) by (interface_name)",
       "legendFormat": "egress errors {{interface_name}}"
      },
      {
       "expr": "sum(rate(interfaces_interface_state_counters_out_discards{region=\"${region}\", source=\"${device}\"}[1m])) by (interface_name)",
       "legendFormat": "egress discards {{interface_name}}"
      },
      {
       "expr": "sum(rate(interfaces_interface_state_counters_in_fcs_errors{region=\"${region}\", source=\"${device}\"}[1m])) by (interface_name)",
       "legendFormat": "ingress fcs errors {{interface_name}}"
      },
      {
       "expr": "sum(rate(interfaces_interface_state_counters_out_fcs_errors{region=\"${region}\", source=\"${device}\"}[1m])) by (interface_name)",
       "legendFormat": "egress fcs errors {{interface_name}}"
      }
     ]
    }
   ]
  }
 ]
}