{
 "title": "Remote Cache",
 "tags": [ "file:cache.json" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "region", "query": { "query": "label_values(up, region)" } },
   {
    "name": "window",
    "label": "Averaging Window",
    "query": "30s, 1m, 5m, 10m, 15m, 30m, 1h, 2h, 4h, 8h, 16h, 1d, 2d, 5d, 7d, 14d, 30d"
   },
   {
    "name": "partition_id",
    "query": {
     "query": "label_values(buildbuddy_remote_cache_disk_cache_partition_capacity_bytes{region=\"$region\"}, partition_id)"
    }
   },
   {
    "name": "cache_name",
    "query": {
     "query": "label_values(buildbuddy_remote_cache_disk_cache_partition_capacity_bytes{region=\"$region\"}, cache_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Remote cache (partition: ${partition_id})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "partition_id",
   "collapsed": true,
   "panels": [
    {
     "title": "Usage (${cache_name})",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "repeat": "cache_name",
     "collapsed": true,
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(buildbuddy_remote_cache_disk_cache_partition_size_bytes{region=\"${region}\",job=\"buildbuddy-app\",partition_id=\"${partition_id}\", cache_name=\"${cache_name}\"}/buildbuddy_remote_cache_disk_cache_partition_capacity_bytes{region=\"${region}\",job=\"buildbuddy-app\",partition_id=\"${partition_id}\", cache_name=\"${cache_name}\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Eviction Age (${cache_name})",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "repeat": "cache_name",
     "collapsed": true,
     "targets": [
      {
       "expr": "sum(increase(buildbuddy_remote_cache_disk_cache_eviction_age_msec_bucket{region=\"$region\", partition_id=\"$partition_id\", cache_name=\"${cache_name}\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Bytes evicted rate (${cache_name})",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "repeat": "cache_name",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(pod_name) (deriv(buildbuddy_remote_cache_disk_cache_partition_size_bytes{region=\"${region}\", cache_name=\"${cache_name}\", partition_id=\"${partition_id}\"}[${window}]))",
       "legendFormat": "total partition size delta {{pod_name}}"
      },
      {
       "expr": "sum by(pod_name) (rate(buildbuddy_remote_cache_disk_cache_partition_size_bytes_evicted{region=\"${region}\", cache_name=\"${cache_name}\", partition_id=\"${partition_id}\"}[${window}]))",
       "legendFormat": "bytes evicted {{pod_name}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Remote cache encryption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Encryption (QPS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_encryption_encrypted_block_count{region=\"${region}\"}[5m]))",
       "legendFormat": "Blocks"
      },
      {
       "expr": "sum(rate(buildbuddy_encryption_encrypted_blob_count{region=\"${region}\"}[5m]))",
       "legendFormat": "Blobs"
      }
     ]
    },
    {
     "title": "Decryption (QPS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_encryption_decrypted_block_count{region=\"${region}\"}[5m]))",
       "legendFormat": "Blocks"
      },
      {
       "expr": "sum(rate(buildbuddy_encryption_decrypted_blob_count{region=\"${region}\"}[5m]))",
       "legendFormat": "Blobs"
      },
      {
       "expr": "sum(rate(buildbuddy_encryption_decryption_error_count{region=\"${region}\"}[5m]))",
       "legendFormat": "Errors"
      }
     ]
    },
    {
     "title": "Key Refreshes (QPS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_encryption_key_refresh_count{region=\"${region}\"}[5m]))",
       "legendFormat": "Attempts"
      },
      {
       "expr": "sum(rate(buildbuddy_encryption_key_refresh_failure_count{region=\"${region}\"}[5m]))",
       "legendFormat": "Errors"
      }
     ]
    },
    {
     "title": "Internal Key Freshness",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "sum(increase(buildbuddy_encryption_key_last_encryption_age_msec_bucket{region=\"${region}\"}[6h])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Remote Cache Migration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Copied Per Second",
     "type": "timeseries",
     "description": "Number of bytes copied from the source to destination cache during a cache migration.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "collapsed": true,
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(cache_type)(rate(buildbuddy_remote_cache_migration_bytes_copied{region=\"${region}\"}[${window}]))",
       "legendFormat": "{{cache_type}}"
      }
     ]
    },
    {
     "title": "Blobs Copied Per Second",
     "type": "timeseries",
     "description": "Number of blobs copied from the source to destination cache during a cache migration.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "collapsed": true,
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(cache_type)(rate(buildbuddy_remote_cache_migration_blobs_copied{region=\"${region}\"}[${window}]))",
       "legendFormat": "{{cache_type}}"
      }
     ]
    },
    {
     "title": "Copy Queue Size",
     "type": "timeseries",
     "description": "Number of digests queued to be copied during a cache migration.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "collapsed": true,
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (pod_name) (buildbuddy_remote_cache_migration_copy_chan_size{region=\"${region}\",namespace=~\"buildbuddy-.*\"})",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Not Found Error Count Per Second",
     "type": "timeseries",
     "description": "Number of not found errors from the destination cache during a cache migration.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "collapsed": true,
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(type)(rate(buildbuddy_remote_cache_migration_not_found_error_count{region=\"${region}\"}[${window}]))",
       "legendFormat": "{{cache_type}}"
      }
     ]
    },
    {
     "title": "Double Read Hit Count Per Second",
     "type": "timeseries",
     "description": "Number of double reads where the source and destination caches hold the same digests during a cache migration.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "collapsed": true,
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(type)(rate(buildbuddy_remote_cache_migration_double_read_hit_count{region=\"${region}\"}[${window}]))",
       "legendFormat": "{{cache_type}}"
      }
     ]
    },
    {
     "title": "Percent of missing artifacts from the destination cache",
     "type": "timeseries",
     "description": "Percent of \"important\" artifacts (from reads) missing from the destination cache. ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "collapsed": true,
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (type) (rate(buildbuddy_remote_cache_migration_not_found_error_count{region=\"${region}\"}[${window}])) / (sum by (type) (rate(buildbuddy_remote_cache_migration_not_found_error_count{region=\"${region}\"}[${window}])) + sum by (type) (rate(buildbuddy_remote_cache_migration_double_read_hit_count{region=\"${region}\"}[${window}])))",
       "legendFormat": "{{cache_type}}"
      }
     ]
    }
   ]
  }
 ]
}