{
 "title": "Cluster Status",
 "tags": [ "file:clusterstatus.json" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "region", "query": { "query": "label_values(up,region)" } }
  ]
 },
 "panels": [
  {
   "title": "Prober Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(cloudprober_success{region=\"${region}\"}[10m])) by (probe) / sum(increase(cloudprober_total{region=\"${region}\"}[10m])) by (probe)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum by (job,version) (buildbuddy_version{region=\"${region}\", job=\"buildbuddy-app\"})",
     "legendFormat": "{{job}} {{version}}"
    },
    {
     "expr": "sum by (job,version) (buildbuddy_version{region=\"${region}\", job=~\".*executor.*\"})",
     "legendFormat": "{{job}} {{version}}"
    },
    {
     "expr": "sum by (job,version) (buildbuddy_version{region=\"${region}\", job=\"cache-proxy\"})",
     "legendFormat": "{{job}} {{version}}"
    }
   ]
  },
  {
   "title": "Cache Proxy Download",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sum(buildbuddy_proxy_action_cache_read_bytes{region=\"${region}\", job=\"cache-proxy\"})) + rate(sum (buildbuddy_proxy_byte_stream_read_bytes{region=\"${region}\", job=\"cache-proxy\"})) + rate(sum(buildbuddy_proxy_content_addressable_storage_bytes{region=\"${region}\", job=\"cache-proxy\", op!=\"BatchUpdateBlobs\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Proxy Upload",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sum(buildbuddy_proxy_action_cache_write_bytes{region=\"${region}\", job=\"cache-proxy\"})) + rate(sum(buildbuddy_proxy_byte_stream_write_bytes{region=\"${region}\", job=\"cache-proxy\"})) + rate(sum(buildbuddy_proxy_content_addressable_storage_bytes{region=\"${region}\", job=\"cache-proxy\", op=\"BatchUpdateBlobs\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Proxy Hit Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(sum(buildbuddy_proxy_action_cache_read_bytes{region=\"${region}\", job=\"cache-proxy\", cache_status=\"hit\"})) + rate(sum(buildbuddy_proxy_byte_stream_read_bytes{region=\"${region}\", job=\"cache-proxy\", cache_status=\"hit\"})) + rate(sum(buildbuddy_proxy_content_addressable_storage_bytes{region=\"${region}\", job=\"cache-proxy\", op!=\"BatchUpdateBlobs\", cache_status=\"hit\"})))/(rate(sum(buildbuddy_proxy_action_cache_read_bytes{region=\"${region}\", job=\"cache-proxy\"})) + rate(sum(buildbuddy_proxy_byte_stream_read_bytes{region=\"${region}\", job=\"cache-proxy\"})) + rate(sum(buildbuddy_proxy_content_addressable_storage_bytes{region=\"${region}\", job=\"cache-proxy\", op!=\"BatchUpdateBlobs\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Proxy TTL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (region) (buildbuddy_remote_cache_disk_cache_last_eviction_age_usec{region=\"${region}\", job=\"cache-proxy\", cache_name=\"pebble_cache\", partition_id=\"default\"}/1e6)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{region=\"${region}\", mode!~\"idle|iowait|steal\", nodename=~\".*executor.*\"}[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{region=\"${region}\", mode!~\"idle|iowait|steal\", nodename=~\".*proxy.*\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor Download",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(buildbuddy_remote_execution_file_download_size_bytes_sum{region=\"${region}\", job=~\".*executor\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor Upload",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(buildbuddy_remote_execution_file_upload_size_bytes_sum{region=\"${region}\", job=~\".*executor\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor Actions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (rate(buildbuddy_remote_execution_count{region=\"${region}\", job=~\".*executor\", status=\"OK\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor autoscaling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(sum by (pod_name) (buildbuddy_remote_execution_queue_length{region=\"${region}\", region!=\"us-sjc\", job=~\".*executor.*\"}))",
     "legendFormat": "Avg executor queue length"
    },
    {
     "expr": "sum(up{region=\"${region}\", job=~\".*executor.*\"})",
     "legendFormat": "Executor instances"
    },
    {
     "expr": "sum(kube_horizontalpodautoscaler_status_desired_replicas{region=\"${region}\", horizontalpodautoscaler=\"executor-autoscaler\"})",
     "legendFormat": "Autoscaler target"
    },
    {
     "expr": "sum(buildbuddy_remote_execution_tasks_executing{region=\"${region}\", job=~\".*executor.*\"})",
     "legendFormat": "Tasks running"
    }
   ]
  },
  {
   "title": "Running Proxies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 42 },
   "targets": [
    {
     "expr": "sum by (region) (up{region=\"${region}\", job=\"cache-proxy\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_horizontalpodautoscaler_status_desired_replicas{region=\"${region}\",horizontalpodautoscaler=\"cache-proxy-autoscaler\"})",
     "legendFormat": "Autoscaler target"
    }
   ]
  }
 ]
}