{
 "title": "Container metrics",
 "tags": [ "file:container-metrics.json" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": { "query": "label_values(up,region)" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_owner{region=\"$region\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Containers close to CPU limit (>80% utilization)",
   "type": "timeseries",
   "description": "These containers are close to their CPU hard limit and may be throttled if they get close to 100%.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (namespace, pod, container) (\n    rate(container_cpu_usage_seconds_total{pod!=\"\", container!=\"\", region=\"${region}\"}[5m])\n)\n    /\nsum by (namespace, pod, container) (\n    container_spec_cpu_quota{pod!=\"\", container!=\"\", region=\"${region}\"}\n        /\n    container_spec_cpu_period{pod!=\"\", container!=\"\", region=\"${region}\"}\n)\n> 0.8",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Containers close to memory limit (>80% utilization)",
   "type": "timeseries",
   "description": "Note: this only includes container RSS usage, not buffer/cache memory.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(\ncontainer_memory_working_set_bytes{pod!=\"\", container!=\"\", region=\"${region}\"}\n    /\ncontainer_spec_memory_limit_bytes{pod!=\"\", container!=\"\", region=\"${region}\"}\n)\n> 0.8",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Containers without resource limits",
   "type": "table",
   "description": "It's *usually* a good idea to set resource limits. Anything listed here does not have a resource limit.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count by (namespace, container) (\n  container_cpu_usage_seconds_total{image!=\"\", region=\"${region}\", container!=\"\"}\n)\nunless\ncount by (namespace, container) (\n  container_spec_cpu_quota{region=\"${region}\"}\n)",
     "legendFormat": "{{namespace}} {{container}}"
    }
   ]
  },
  {
   "title": "Unused CPU (limit - used; cores)",
   "type": "timeseries",
   "description": "Can help identify oversized containers.",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "sum by (namespace, container) (\n    container_spec_cpu_quota{region=\"${region}\", container!=\"\"} / container_spec_cpu_period{region=\"${region}\", container!=\"\"}\n)\n-\nsum by (namespace, container) (rate(container_cpu_usage_seconds_total{region=\"${region}\", container!=\"\"}[1m]))",
     "legendFormat": "{{namespace}}/{{container}}"
    }
   ]
  },
  {
   "title": "Unused memory (limit - used)",
   "type": "timeseries",
   "description": "Page cache memory is considered \"used\" memory for the purposes of this chart.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, container) (container_spec_memory_limit_bytes{region=\"${region}\", container!=\"\"} > 0)\n-\nsum by (namespace, container) (container_memory_usage_bytes{region=\"${region}\", container!=\"\"})",
     "legendFormat": "{{namespace}}/{{container}}"
    }
   ]
  },
  {
   "title": "Resource usage ($namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "repeat": "namespace",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage by container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum by (pod, container) (rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\", region=\"${region}\", container!=\"\"}[1m]))",
       "legendFormat": "{{pod}}/{{container}} (usage)"
      },
      {
       "expr": "sum by (pod, container) (\n    container_spec_cpu_quota{namespace=\"${namespace}\", region=\"${region}\", container!=\"\"}\n    / container_spec_cpu_period{namespace=\"${namespace}\", region=\"${region}\", container!=\"\"}\n)",
       "legendFormat": "{{pod}}/{{container}} (limit)"
      }
     ]
    },
    {
     "title": "Memory usage (working set) by container",
     "type": "timeseries",
     "description": "Working set memory is memory that cannot be easily reclaimed. If a container's working set  memory reaches its memory limit, it is at risk of being OOM-killed.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod, container) (container_memory_working_set_bytes{namespace=\"$namespace\", region=\"$region\", container!=\"\"})",
       "legendFormat": "{{pod}}/{{container}} (usage)"
      },
      {
       "expr": "sum by (pod, container) (container_spec_memory_limit_bytes{namespace=\"$namespace\", region=\"$region\", container!=\"\"})",
       "legendFormat": "{{pod}}/{{container}} (limit)"
      }
     ]
    }
   ]
  }
 ]
}