{
 "title": "Envoy",
 "tags": [ "file:envoy.json" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "region",
    "query": {
     "query": "label_values(envoy_server_initialization_time_ms_count,region)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(envoy_cluster_upstream_rq,envoy_cluster_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{region=\"${region}\", namespace=\"projectcontour\", container=\"envoy\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{region=\"${region}\", namespace=\"projectcontour\", container=\"envoy\"}) by (pod)",
     "legendFormat": "{{pod}} limit"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{region=\"${region}\", namespace=\"projectcontour\", container=\"envoy\"}[1m])) by (pod)",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum(container_spec_cpu_quota{region=\"${region}\", namespace=\"projectcontour\", container=\"envoy\"}) by (pod) / sum(container_spec_cpu_period{region=\"${region}\", namespace=\"projectcontour\", container=\"envoy\"}) by (pod)",
     "legendFormat": "{{pod}} limit"
    }
   ]
  },
  {
   "title": "Cluster ${cluster}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_xx{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (envoy_response_code_class)\n",
       "legendFormat": "{{envoy_response_code_class}}xx"
      }
     ]
    },
    {
     "title": "QPS by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_xx{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Aggregate request latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (le))",
       "legendFormat": "95p"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (le))",
       "legendFormat": "99p"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(envoy_cluster_upstream_rq_time_bucket{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (le))",
       "legendFormat": "50p"
      }
     ]
    },
    {
     "title": "Circuit breakers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "sum(envoy_cluster_circuit_breakers_default_cx_open{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m]) by (pod_name)",
       "legendFormat": "default_cx_open {{pod_name}}"
      },
      {
       "expr": "sum(envoy_cluster_circuit_breakers_default_cx_pool_open{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m]) by (pod_name)",
       "legendFormat": "default_cx_pool_open {{pod_name}}"
      },
      {
       "expr": "sum(envoy_cluster_circuit_breakers_default_rq_open{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m]) by (pod_name)",
       "legendFormat": "default_rq_open {{pod_name}}"
      },
      {
       "expr": "sum(envoy_cluster_circuit_breakers_default_rq_pending_open{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m]) by (pod_name)",
       "legendFormat": "default_rq_pending_open {{pod_name}}"
      },
      {
       "expr": "sum(envoy_cluster_circuit_breakers_default_rq_retry_open{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m]) by (pod_name)",
       "legendFormat": "default_rq_retry_open {{pod_name}}"
      },
      {
       "expr": "sum(envoy_cluster_circuit_breakers_high_cx_open{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m]) by (pod_name)",
       "legendFormat": "high_cx_open {{pod_name}}"
      },
      {
       "expr": "sum(envoy_cluster_circuit_breakers_high_cx_pool_open{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m]) by (pod_name)",
       "legendFormat": "high_cx_pool_open {{pod_name}}"
      },
      {
       "expr": "sum(envoy_cluster_circuit_breakers_high_rq_open{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m]) by (pod_name)",
       "legendFormat": "high_rq_open {{pod_name}}"
      },
      {
       "expr": "sum(envoy_cluster_circuit_breakers_high_rq_pending_open{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m]) by (pod_name)",
       "legendFormat": "high_rq_pending_open {{pod_name}}"
      },
      {
       "expr": "sum(envoy_cluster_circuit_breakers_high_rq_retry_open{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m]) by (pod_name)",
       "legendFormat": "high_rq_retry_open {{pod_name}}"
      }
     ]
    },
    {
     "title": "Flow control",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_flow_control_backed_up_total{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)",
       "legendFormat": "backed_up {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_flow_control_drained_total{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "drained {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_flow_control_paused_reading_total{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "paused_reading {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_flow_control_resumed_reading_total{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "resumed_reading {{pod_name}}"
      }
     ]
    },
    {
     "title": "Upstream events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_maintenance_mode{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "rq_maintenance_mode {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_max_duration_reached{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "rq_max_duration_reached {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_pending_failure_eject{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "rq_pending_failure_eject {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_pending_overflow{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "rq_pending_overflow {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_pending_total{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "rq_pending_total {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_per_try_idle_timeout{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "rq_per_try_idle_timeout {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_per_try_timeout{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "rq_per_try_timeout {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_retry{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "rq_retry {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_retry_backoff_exponential{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "rq_retry_backoff_exponential {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_retry_backoff_ratelimited{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "rq_retry_backoff_ratelimited {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_retry_limit_exceeded{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "rq_retry_limit_exceeded {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_retry_overflow{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "rq_retry_overflow {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_retry_success{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "rq_retry_success {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_timeout{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "rq_timeout {{pod_name}}"
      }
     ]
    },
    {
     "title": "Throughput (received from backends)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_rx_bytes_total{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Throughput (sent to backends)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_tx_bytes_total{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Bytes buffered from backend",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(envoy_cluster_upstream_cx_rx_bytes_buffered{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m]) by (pod_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bytes buffered to backend",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(envoy_cluster_upstream_cx_tx_bytes_buffered{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m]) by (pod_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP/2 events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_http2_dropped_headers_with_underscores{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)",
       "legendFormat": "dropped_headers_with_underscores {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_http2_goaway_sent{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)",
       "legendFormat": "goaway_sent {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_http2_header_overflow{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)",
       "legendFormat": "header_overflow {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_http2_headers_cb_no_stream{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "headers_cb_no_stream {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_http2_inbound_empty_frames_flood{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "inbound_empty_frames_flood {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_http2_inbound_priority_frames_flood{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "inbound_priority_frames_flood {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_http2_inbound_window_update_frames_flood{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "inbound_window_update_frames_flood {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_http2_keepalive_timeout{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "keepalive_timeout {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_http2_metadata_empty_frames{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "metadata_empty_frames {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_http2_outbound_control_flood{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "outbound_control_flood {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_http2_outbound_flood{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "outbound_flood {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_http2_requests_rejected_with_underscores_in_headers{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "requests_rejected_with_underscores_in_headers {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_http2_rx_messaging_error{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "rx_messaging_error {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_http2_stream_refused_errors{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "stream_refused_errors {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_http2_trailers{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "trailers {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_http2_tx_flush_timeout{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "tx_flush_timeout {{pod_name}}"
      }
     ]
    },
    {
     "title": "New backend connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_http1_total{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)",
       "legendFormat": "http/1 {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_http2_total{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)",
       "legendFormat": "http/2 {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_http3_total{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "http/3 {{pod_name}}"
      }
     ]
    },
    {
     "title": "Cluster events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_close_notify{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "cx_close_notify {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_connect_attempts_exceeded{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "cx_connect_attempts_exceeded {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_connect_fail{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "cx_connect_fail {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_connect_timeout{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "cx_connect_timeout {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_connect_with_0_rtt{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "cx_connect_with_0_rtt {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_destroy{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "cx_destroy {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_destroy_local{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "cx_destroy_local {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_destroy_local_with_active_rq{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "cx_destroy_local_with_active_rq {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_destroy_remote{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "cx_destroy_remote {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_destroy_remote_with_active_rq{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "cx_destroy_remote_with_active_rq {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_destroy_with_active_rq{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "cx_destroy_with_active_rq {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_idle_timeout{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "cx_idle_timeout {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_max_duration_reached{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "cx_max_duration_reached {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_max_requests{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "cx_max_requests {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_none_healthy{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "cx_none_healthy {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_overflow{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "cx_overflow {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_pool_overflow{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "cx_pool_overflow {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_protocol_error{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "cx_protocol_error {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_internal_redirect_failed_total{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "internal_redirect_failed_total {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_internal_redirect_succeeded_total{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "internal_redirect_succeeded_total {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_0rtt{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "rq_0rtt {{pod_name}}"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_cancelled{region=\"${region}\", envoy_cluster_name=\"${cluster}\", namespace=\"projectcontour\"}[1m])) by (pod_name)\n",
       "legendFormat": "rq_cancelled {{pod_name}}"
      }
     ]
    }
   ]
  }
 ]
}