{
 "title": "Execution Stats",
 "tags": [ "file:execution-stats.json" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "group_id", "label": "Group ID", "query": "%" },
   { "name": "action_mnemonic", "label": "Action Mnemonic", "query": "%" },
   { "name": "self_hosted", "label": "Self Hosted", "query": "false" },
   { "name": "region", "label": "Region", "query": "%" },
   { "name": "effective_isolation_type", "label": "Effective Isolation Type", "query": "%" },
   {
    "name": "other_filters",
    "label": "Other Filters",
    "query": "command NOT LIKE 'remote%' AND command NOT LIKE 'workflow%'"
   },
   { "name": "group_by", "label": "Group By Columns", "query": "1" }
  ]
 },
 "panels": [
  {
   "title": "Action completion count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(updated_at) as \"time\",\n  ${group_by},\n  COUNT(*) AS executions\nFROM \"buildbuddy_prod\".\"ExecutionsView\"\nWHERE true\n  AND group_id LIKE '${group_id}'\n  AND updated_at_usec BETWEEN toUnixTimestamp64Micro($__fromTime_ms) AND toUnixTimestamp64Micro($__toTime_ms)\n  AND effective_isolation_type LIKE '${effective_isolation_type}'\n  AND action_mnemonic LIKE '${action_mnemonic}'\n  AND region LIKE '${region}'\n  AND self_hosted = ${self_hosted}\n  AND ${other_filters}\nGROUP by time, ${group_by}\nORDER BY time"
    }
   ]
  },
  {
   "title": "Total CPU time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(updated_at) as \"time\",\n  ${group_by},\n  SUM(cpu_nanos / 1e9) AS cpu_s\nFROM \"buildbuddy_prod\".\"ExecutionsView\"\nWHERE true\n  AND group_id LIKE '${group_id}'\n  AND updated_at_usec BETWEEN toUnixTimestamp64Micro($__fromTime_ms) AND toUnixTimestamp64Micro($__toTime_ms)\n  AND effective_isolation_type LIKE '${effective_isolation_type}'\n  AND action_mnemonic LIKE '${action_mnemonic}'\n  AND region LIKE '${region}'\n  AND self_hosted = ${self_hosted}\n  AND ${other_filters}\nGROUP by time, ${group_by}\nORDER BY time"
    }
   ]
  },
  {
   "title": "CPUs occupied",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(updated_at) as \"time\",\n  ${group_by},\n  SUM(cpu_nanos / 1e9) / $__interval_s AS cpus\nFROM \"buildbuddy_prod\".\"ExecutionsView\"\nWHERE true\n  AND group_id LIKE '${group_id}'\n  AND updated_at_usec BETWEEN toUnixTimestamp64Micro($__fromTime_ms) AND toUnixTimestamp64Micro($__toTime_ms)\n  AND effective_isolation_type LIKE '${effective_isolation_type}'\n  AND action_mnemonic LIKE '${action_mnemonic}'\n  AND region LIKE '${region}'\n  AND self_hosted = ${self_hosted}\n  AND ${other_filters}\nGROUP by time, ${group_by}\nORDER BY time"
    }
   ]
  },
  {
   "title": "Total execution wall time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(updated_at) as \"time\",\n  ${group_by},\n  SUM(execution_duration) AS exec_s\nFROM \"buildbuddy_prod\".\"ExecutionsView\"\nWHERE true\n  AND group_id LIKE '${group_id}'\n  AND updated_at_usec BETWEEN toUnixTimestamp64Micro($__fromTime_ms) AND toUnixTimestamp64Micro($__toTime_ms)\n  AND effective_isolation_type LIKE '${effective_isolation_type}'\n  AND action_mnemonic LIKE '${action_mnemonic}'\n  AND region LIKE '${region}'\n  AND self_hosted = ${self_hosted}\n  AND ${other_filters}\nGROUP by time, ${group_by}\nORDER BY time"
    }
   ]
  },
  {
   "title": "Executors Occupied",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(updated_at) as \"time\",\n  ${group_by},\n  SUM(worker_duration) / $__interval_s AS executors\nFROM \"buildbuddy_prod\".\"ExecutionsView\"\nWHERE true\n  AND group_id LIKE '${group_id}'\n  AND updated_at_usec BETWEEN toUnixTimestamp64Micro($__fromTime_ms) AND toUnixTimestamp64Micro($__toTime_ms)\n  AND effective_isolation_type LIKE '${effective_isolation_type}'\n  AND action_mnemonic LIKE '${action_mnemonic}'\n  AND region LIKE '${region}'\n  AND self_hosted = ${self_hosted}\n  AND ${other_filters}\nGROUP by time, ${group_by}\nORDER BY time"
    }
   ]
  },
  {
   "title": "Queued Actions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(updated_at) as \"time\",\n  ${group_by},\n  SUM(queued_duration) / $__interval_s AS queued_actions\nFROM \"buildbuddy_prod\".\"ExecutionsView\"\nWHERE true\n  AND group_id LIKE '${group_id}'\n  AND updated_at_usec BETWEEN toUnixTimestamp64Micro($__fromTime_ms) AND toUnixTimestamp64Micro($__toTime_ms)\n  AND effective_isolation_type LIKE '${effective_isolation_type}'\n  AND action_mnemonic LIKE '${action_mnemonic}'\n  AND region LIKE '${region}'\n  AND self_hosted = ${self_hosted}\n  AND ${other_filters}\nGROUP by time, ${group_by}\nORDER BY time"
    }
   ]
  },
  {
   "title": "Error ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(updated_at) as \"time\",\n  ${group_by},\n  countIf(status_code!=0) / COUNT(*) AS error_ratio\nFROM \"buildbuddy_prod\".\"ExecutionsView\"\nWHERE true\n  AND group_id LIKE '${group_id}'\n  AND updated_at_usec BETWEEN toUnixTimestamp64Micro($__fromTime_ms) AND toUnixTimestamp64Micro($__toTime_ms)\n  AND effective_isolation_type LIKE '${effective_isolation_type}'\n  AND action_mnemonic LIKE '${action_mnemonic}'\n  AND region LIKE '${region}'\n  AND self_hosted = ${self_hosted}\n  AND ${other_filters}\nGROUP by time, ${group_by}\nORDER BY time"
    }
   ]
  },
  {
   "title": "Failure ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(updated_at) as \"time\",\n  ${group_by},\n  countIf(exit_code!=0) / COUNT(*) AS failure_ratio\nFROM \"buildbuddy_prod\".\"ExecutionsView\"\nWHERE true\n  AND group_id LIKE '${group_id}'\n  AND updated_at_usec BETWEEN toUnixTimestamp64Micro($__fromTime_ms) AND toUnixTimestamp64Micro($__toTime_ms)\n  AND effective_isolation_type LIKE '${effective_isolation_type}'\n  AND action_mnemonic LIKE '${action_mnemonic}'\n  AND region LIKE '${region}'\n  AND self_hosted = ${self_hosted}\n  AND ${other_filters}\n  AND status_code=0\nGROUP by time, ${group_by}\nORDER BY time"
    }
   ]
  },
  {
   "title": "Downloaded bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(updated_at) as \"time\",\n  ${group_by},\n  SUM(file_download_size_bytes) AS downloaded_bytes\nFROM \"buildbuddy_prod\".\"ExecutionsView\"\nWHERE true\n  AND group_id LIKE '${group_id}'\n  AND updated_at_usec BETWEEN toUnixTimestamp64Micro($__fromTime_ms) AND toUnixTimestamp64Micro($__toTime_ms)\n  AND effective_isolation_type LIKE '${effective_isolation_type}'\n  AND action_mnemonic LIKE '${action_mnemonic}'\n  AND region LIKE '${region}'\n  AND self_hosted = ${self_hosted}\n  AND ${other_filters}\nGROUP by time, ${group_by}\nORDER BY time"
    }
   ]
  },
  {
   "title": "Uploaded bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(updated_at) as \"time\",\n  ${group_by},\n  SUM(file_upload_size_bytes) AS downloaded_bytes\nFROM \"buildbuddy_prod\".\"ExecutionsView\"\nWHERE true\n  AND group_id LIKE '${group_id}'\n  AND updated_at_usec BETWEEN toUnixTimestamp64Micro($__fromTime_ms) AND toUnixTimestamp64Micro($__toTime_ms)\n  AND effective_isolation_type LIKE '${effective_isolation_type}'\n  AND action_mnemonic LIKE '${action_mnemonic}'\n  AND region LIKE '${region}'\n  AND self_hosted = ${self_hosted}\n  AND ${other_filters}\nGROUP by time, ${group_by}\nORDER BY time"
    }
   ]
  },
  {
   "title": "Network bytes received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(updated_at) as \"time\",\n  ${group_by},\n  SUM(network_bytes_received) AS received\nFROM \"buildbuddy_prod\".\"ExecutionsView\"\nWHERE true\n  AND group_id LIKE '${group_id}'\n  AND updated_at_usec BETWEEN toUnixTimestamp64Micro($__fromTime_ms) AND toUnixTimestamp64Micro($__toTime_ms)\n  AND effective_isolation_type LIKE '${effective_isolation_type}'\n  AND action_mnemonic LIKE '${action_mnemonic}'\n  AND region LIKE '${region}'\n  AND self_hosted = ${self_hosted}\n  AND ${other_filters}\nGROUP by time, ${group_by}\nORDER BY time"
    }
   ]
  },
  {
   "title": "Network bytes sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(updated_at) as \"time\",\n  ${group_by},\n  SUM(network_bytes_sent) AS sent\nFROM \"buildbuddy_prod\".\"ExecutionsView\"\nWHERE true\n  AND group_id LIKE '${group_id}'\n  AND updated_at_usec BETWEEN toUnixTimestamp64Micro($__fromTime_ms) AND toUnixTimestamp64Micro($__toTime_ms)\n  AND effective_isolation_type LIKE '${effective_isolation_type}'\n  AND action_mnemonic LIKE '${action_mnemonic}'\n  AND region LIKE '${region}'\n  AND self_hosted = ${self_hosted}\n  AND ${other_filters}\nGROUP by time, ${group_by}\nORDER BY time"
    }
   ]
  }
 ]
}