{
 "title": "Global Status",
 "tags": [ "file:globalstatus.json" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "region", "query": { "query": "label_values(up,region)" } }
  ]
 },
 "panels": [
  {
   "title": "Prober Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(cloudprober_success{region=~\"${region}\"}[10m])) by (region, probe) / sum(increase(cloudprober_total{region=~\"${region}\"}[10m])) by (region, probe)",
     "legendFormat": "{{region}} {{probe}}"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "sum by (region, job,version) (buildbuddy_version{region=~\"${region}\", job=~\"(buildbuddy-app|cache-proxy|.*executor.*)\"})",
     "legendFormat": "{{region}} {{job}} {{version}}"
    }
   ]
  },
  {
   "title": "Cache Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(buildbuddy_remote_cache_download_size_bytes_sum{job=\"buildbuddy-app\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(buildbuddy_remote_cache_upload_size_bytes_sum{job=\"buildbuddy-app\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache TTL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(buildbuddy_remote_cache_disk_cache_last_eviction_age_usec{job=\"buildbuddy-app\", cache_name=\"pebble_gcs_cache\", partition_id=\"default\"}/1e6)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Proxy Download",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sum(buildbuddy_proxy_action_cache_read_bytes{region=~\"${region}\", job=\"cache-proxy\"})) + rate(sum (buildbuddy_proxy_byte_stream_read_bytes{region=~\"${region}\", job=\"cache-proxy\"})) + rate(sum(buildbuddy_proxy_content_addressable_storage_bytes{region=~\"${region}\", job=\"cache-proxy\", op!=\"BatchUpdateBlobs\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Proxy Upload",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sum(buildbuddy_proxy_action_cache_write_bytes{region=~\"${region}\", job=\"cache-proxy\"})) + rate(sum(buildbuddy_proxy_byte_stream_write_bytes{region=~\"${region}\", job=\"cache-proxy\"})) + rate(sum(buildbuddy_proxy_content_addressable_storage_bytes{region=~\"${region}\", job=\"cache-proxy\", op=\"BatchUpdateBlobs\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Proxy Hit Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(sum(buildbuddy_proxy_action_cache_read_bytes{region=~\"${region}\", job=\"cache-proxy\", cache_status=\"hit\"})) + rate(sum(buildbuddy_proxy_byte_stream_read_bytes{region=~\"${region}\", job=\"cache-proxy\", cache_status=\"hit\"})) + rate(sum(buildbuddy_proxy_content_addressable_storage_bytes{region=~\"${region}\", job=\"cache-proxy\", op!=\"BatchUpdateBlobs\", cache_status=\"hit\"})))/(rate(sum(buildbuddy_proxy_action_cache_read_bytes{region=~\"${region}\", job=\"cache-proxy\"})) + rate(sum(buildbuddy_proxy_byte_stream_read_bytes{region=~\"${region}\", job=\"cache-proxy\"})) + rate(sum(buildbuddy_proxy_content_addressable_storage_bytes{region=~\"${region}\", job=\"cache-proxy\", op!=\"BatchUpdateBlobs\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Proxy TTL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (region) (buildbuddy_remote_cache_disk_cache_last_eviction_age_usec{region=~\"${region}\", job=\"cache-proxy\", cache_name=\"pebble_cache\", partition_id=\"default\"}/1e6)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invocation QPS (OK)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (region) (rate(buildbuddy_invocation_count{invocation_status=\"success\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{region=~\"${region}\", mode!~\"idle|iowait|steal\", nodename=~\".*app.*\"}[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{region=~\"${region}\", mode!~\"idle|iowait|steal\", nodename=~\".*executor.*\"}[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{region=~\"${region}\", mode!~\"idle|iowait|steal\", nodename=~\".*cache-proxy.*\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(buildbuddy_remote_execution_file_download_size_bytes_sum{region=~\"${region}\", job=~\".*executor\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(buildbuddy_remote_execution_file_upload_size_bytes_sum{region=~\"${region}\", job=~\".*executor\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor Actions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (rate(buildbuddy_remote_execution_count{region=~\"${region}\", job=~\".*executor\", status=\"OK\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executors by Region",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 7, "y": 45 },
   "targets": [
    {
     "expr": "sum by (region) (up{job=~\".*executor.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executors by OS/Arch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 54 },
   "targets": [
    {
     "expr": "sum(up{job=\"mac-executor\", nodename=~\"macstadium-iteration_inc_1|macstadium-iteration_inc_2|macstadium-iteration_inc_3|macstadium-mobile_native_foundation_1|macstadium-mobile_native_foundation_6\"})",
     "legendFormat": "darwin/amd64"
    },
    {
     "expr": "sum(up{job=\"mac-executor\", nodename!~\"macstadium-iteration_inc_1|macstadium-iteration_inc_2|macstadium-iteration_inc_3|macstadium-mobile_native_foundation_1|macstadium-mobile_native_foundation_6\"})",
     "legendFormat": "darwin/arm64"
    },
    {
     "expr": "sum(up{job=~\".*executor.*\", job!~\"mac-executor|executor-arm64\"})",
     "legendFormat": "linux/amd64"
    },
    {
     "expr": "sum(up{job=~\".*executor-arm64.*\"})",
     "legendFormat": "linux/arm64"
    }
   ]
  },
  {
   "title": "Executors Spot vs Non-Spot",
   "type": "timeseries",
   "description": "Spot (green) vs Non-spot (yellow) executors",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 62 },
   "targets": [
    {
     "expr": "sum by (pooltype) (\n    label_replace(\n    label_replace(\n    label_replace(\n    label_replace(\n        node_uname_info{nodename=~\".*executor.*\", region=~\"(us-central1|us-west1|us-west2)\"},\n        \"nodepool\", \"$2\", \"nodename\", \"^gke-(dev|prod)-[^-]*-(.*)-[0-9a-f]{8}-(grp-)?.{4}$\"\n    ),\n        \"pooltype\", \"spot\", \"nodepool\", \"^spot-.*$\"\n    ),\n        \"pooltype\", \"non-spot\", \"nodepool\", \"^(bb|executor)-.*$\"\n    ),\n        \"pooltype\", \"workflows\", \"nodepool\", \"^(workflow-executor)-.*$\"\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor autoscaling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(sum by (pod_name) (buildbuddy_remote_execution_queue_length{region!=\"us-sjc\", job=\"executor\"}))",
     "legendFormat": "Avg executor queue length"
    },
    {
     "expr": "sum(up{job=\"executor\"})",
     "legendFormat": "Executor instances"
    },
    {
     "expr": "sum(kube_horizontalpodautoscaler_status_desired_replicas{horizontalpodautoscaler=\"executor-autoscaler\"})",
     "legendFormat": "Autoscaler target"
    },
    {
     "expr": "sum(buildbuddy_remote_execution_tasks_executing{job=\"executor\"})",
     "legendFormat": "Tasks running"
    }
   ]
  },
  {
   "title": "Running Proxies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 78 },
   "targets": [
    {
     "expr": "sum by (region) (up{job=~\"cache-proxy.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_horizontalpodautoscaler_status_desired_replicas{horizontalpodautoscaler=~\"cache-proxy-autoscaler.*\"}) + sum(up{region=\"us-sjc\", job=\"cache-proxy.*\"}) + sum(up{region=\"us-nuq\", job=\"cache-proxy.*\"}) + sum(up{region=~\"^aws-.*\", job=\"cache-proxy.*\"})",
     "legendFormat": "Autoscaler target"
    }
   ]
  }
 ]
}