{
 "title": "Kubernetes Nodes",
 "tags": [ "file:nodes.json" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "region", "query": { "query": "label_values(up, region)" } },
   {
    "name": "window",
    "label": "Averaging Window",
    "query": "30s, 1m, 5m, 10m, 15m, 30m, 1h, 2h, 4h, 8h, 16h, 1d, 2d, 5d, 7d, 14d, 30d"
   },
   {
    "name": "kubenode",
    "query": {
     "query": "label_values(node_uname_info{region=\"$region\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node disk/network IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${kubenode} disk and network IO",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "repeat": "kubenode",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total[1m]) * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})",
       "legendFormat": "{{device}} reads"
      },
      {
       "expr": "rate(node_disk_written_bytes_total[1m]) * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})",
       "legendFormat": "{{device}} writes"
      },
      {
       "expr": "rate(node_network_receive_bytes_total{device=~\"ens.*\"}[1m]) * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})",
       "legendFormat": "{{device}} rx"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{device=~\"ens.*\"}[1m]) * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})",
       "legendFormat": "{{device}} tx"
      },
      {
       "expr": "1 - (avg by(mode) ((rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})))",
       "legendFormat": "cpu"
      }
     ]
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${kubenode} memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "repeat": "kubenode",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_wired_bytes * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})",
       "legendFormat": "Wired memory"
      },
      {
       "expr": "node_memory_compressed_bytes * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})",
       "legendFormat": "Compressed memory"
      },
      {
       "expr": "node_memory_active_bytes * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})",
       "legendFormat": "Active memory"
      },
      {
       "expr": "node_memory_inactive_bytes * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})",
       "legendFormat": "Inactive memory"
      },
      {
       "expr": "node_memory_free_bytes * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})",
       "legendFormat": "Free memory"
      }
     ]
    }
   ]
  },
  {
   "title": "Node swap usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${kubenode} swap usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "repeat": "kubenode",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_swap_used_bytes * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})",
       "legendFormat": "Swap memory used"
      }
     ]
    }
   ]
  },
  {
   "title": "Node swap rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${kubenode} Swap rate (${window})",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "repeat": "kubenode",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(node_memory_swapped_in_bytes_total[${window}]) * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})",
       "legendFormat": "Swap in rate"
      },
      {
       "expr": "rate(node_memory_swapped_out_bytes_total[${window}]) * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=\"${kubenode}\"})",
       "legendFormat": "Swap out rate"
      }
     ]
    }
   ]
  }
 ]
}