{
 "title": "Raft",
 "tags": [ "file:raft.json" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "region", "query": { "query": "label_values(up,region)" } },
   {
    "name": "window",
    "label": "Averaging Window",
    "query": "30s, 1m, 5m, 10m, 15m, 30m, 1h, 2h, 4h, 8h, 16h, 1d, 2d, 5d, 7d, 14d, 30d"
   },
   { "name": "quantile", "query": "0.5,0.75,0.9,0.95,0.99" },
   {
    "name": "partition_id",
    "query": {
     "query": "label_values(buildbuddy_remote_cache_disk_cache_partition_capacity_bytes{namespace=\"$namespace\"},partition_id)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(buildbuddy_raft_ranges,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Meta Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Mix",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_cache_method_handled_total{region=\"${region}\", job=\"buildbuddy-app\"}[${window}])) by (cache_method)\n",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "/GetMulti",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(buildbuddy_remote_cache_method_handling_usec_bucket{region=\"${region}\", job=\"buildbuddy-app\", cache_method=\"GetMulti\"}[${window}])) by (le)\n)",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(buildbuddy_remote_cache_method_handling_usec_bucket{region=\"${region}\", job=\"buildbuddy-app\", cache_method=\"GetMulti\"}[${window}])) by (le)\n)",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(buildbuddy_remote_cache_method_handling_usec_bucket{region=\"${region}\", job=\"buildbuddy-app\", cache_method=\"GetMulti\"}[${window}])) by (le)\n)",
       "legendFormat": "P50"
      },
      {
       "expr": "sum(rate(buildbuddy_remote_cache_method_handled_total{region=\"${region}\", job=\"buildbuddy-app\", cache_method=\"GetMulti\"}[${window}]))",
       "legendFormat": "QPS"
      }
     ]
    },
    {
     "title": "/Get",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(buildbuddy_remote_cache_method_handling_usec_bucket{region=\"${region}\", job=\"buildbuddy-app\", cache_method=\"Get\"}[${window}])) by (le)\n)",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(buildbuddy_remote_cache_method_handling_usec_bucket{region=\"${region}\", job=\"buildbuddy-app\", cache_method=\"Get\"}[${window}])) by (le)\n)",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(buildbuddy_remote_cache_method_handling_usec_bucket{region=\"${region}\", job=\"buildbuddy-app\", cache_method=\"Get\"}[${window}])) by (le)\n)",
       "legendFormat": "P50"
      },
      {
       "expr": "sum(rate(buildbuddy_remote_cache_method_handled_total{region=\"${region}\", job=\"buildbuddy-app\", cache_method=\"Get\"}[${window}]))",
       "legendFormat": "QPS"
      }
     ]
    },
    {
     "title": "/SetMulti",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(buildbuddy_remote_cache_method_handling_usec_bucket{region=\"${region}\", job=\"buildbuddy-app\", cache_method=\"SetMulti\"}[${window}])) by (le)\n)",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(buildbuddy_remote_cache_method_handling_usec_bucket{region=\"${region}\", job=\"buildbuddy-app\", cache_method=\"SetMulti\"}[${window}])) by (le)\n)",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(buildbuddy_remote_cache_method_handling_usec_bucket{region=\"${region}\", job=\"buildbuddy-app\", cache_method=\"SetMulti\"}[${window}])) by (le)\n)",
       "legendFormat": "P50"
      },
      {
       "expr": "sum(rate(buildbuddy_remote_cache_method_handled_total{region=\"${region}\", job=\"buildbuddy-app\", cache_method=\"SetMulti\"}[${window}]))",
       "legendFormat": "QPS"
      }
     ]
    },
    {
     "title": "/FindMissing",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(buildbuddy_remote_cache_method_handling_usec_bucket{region=\"${region}\", job=\"buildbuddy-app\", cache_method=\"FindMissing\"}[${window}])) by (le)\n)",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(buildbuddy_remote_cache_method_handling_usec_bucket{region=\"${region}\", job=\"buildbuddy-app\", cache_method=\"FindMissing\"}[${window}])) by (le)\n)",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(buildbuddy_remote_cache_method_handling_usec_bucket{region=\"${region}\", job=\"buildbuddy-app\", cache_method=\"FindMissing\"}[${window}])) by (le)\n)",
       "legendFormat": "P50"
      },
      {
       "expr": "sum(rate(buildbuddy_remote_cache_method_handled_total{region=\"${region}\", job=\"buildbuddy-app\", cache_method=\"FindMissing\"}[${window}]))",
       "legendFormat": "QPS"
      }
     ]
    }
   ]
  },
  {
   "title": "mdload",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Final Error Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2796 },
     "targets": [
      {
       "expr": "sum(increase(buildbuddy_mdload_final_error_count{region=\"${region}\"}[${window}])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Total Error Count (including retries)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2796 },
     "targets": [
      {
       "expr": "sum(increase(buildbuddy_mdload_total_error_count{region=\"${region}\"}[${window}])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Metadata Server Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 475 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - (avg by(mode,nodename) ((rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * on(instance) group_left(nodename) (node_uname_info{region=\"${region}\", nodename=~\"^gke-.*-mds-.*-([0-9a-f]{8})-(grp-)?[0-9a-z]{4}$\"})))",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "pod  <> nhid <>  gke node",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 475 },
     "targets": [
      {
       "expr": "avg(buildbuddy_raft_ranges{region=\"${region}\", namespace=\"${namespace}\"}) by (node_host_id, pod_name)\n  * on(pod_name) group_left(node)\n  label_replace(\n    kube_pod_info{namespace=\"${namespace}\", pod=~\"metadata-server-.*\"},\n    \"pod_name\", \"$1\", \"pod\", \"(.*)\"\n  )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "instances",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 483 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(up{region=\"${region}\", job=\"metadata-server\", namespace=\"${namespace}\"})",
       "legendFormat": "Up"
      },
      {
       "expr": "sum(kube_pod_status_ready{region=\"${region}\", pod=~\"metadata-server-([0-9a-f]{8,10}-.*|[0-9]+)$\", namespace=\"${namespace}\"})",
       "legendFormat": "Ready"
      }
     ]
    },
    {
     "title": "/Set",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 483 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{region=\"${region}\", namespace=\"${namespace}\", grpc_service=\"metadata.service.MetadataService\", grpc_method=\"Set\"}[${window}])) by (le)\n)",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(grpc_server_handling_seconds_bucket{region=\"${region}\", namespace=\"${namespace}\", grpc_service=\"metadata.service.MetadataService\", grpc_method=\"Set\"}[${window}])) by (le)\n)",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(grpc_server_handling_seconds_bucket{region=\"${region}\", namespace=\"${namespace}\", grpc_service=\"metadata.service.MetadataService\", grpc_method=\"Set\"}[${window}])) by (le)\n)",
       "legendFormat": "P50"
      },
      {
       "expr": "sum(rate(grpc_server_handled_total{region=\"${region}\", namespace=\"${namespace}\", grpc_service=\"metadata.service.MetadataService\", grpc_method=\"Set\"}[${window}]))",
       "legendFormat": "QPS"
      }
     ]
    },
    {
     "title": "/Get",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 667 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{region=\"${region}\", namespace=\"${namespace}\", grpc_service=\"metadata.service.MetadataService\", grpc_method=\"Get\"}[${window}])) by (le)\n)",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(grpc_server_handling_seconds_bucket{region=\"${region}\", namespace=\"${namespace}\", grpc_service=\"metadata.service.MetadataService\", grpc_method=\"Get\"}[${window}])) by (le)\n)",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(grpc_server_handling_seconds_bucket{region=\"${region}\", namespace=\"${namespace}\", grpc_service=\"metadata.service.MetadataService\", grpc_method=\"Get\"}[${window}])) by (le)\n)",
       "legendFormat": "P50"
      },
      {
       "expr": "sum(rate(grpc_server_handled_total{region=\"${region}\", namespace=\"${namespace}\", grpc_service=\"metadata.service.MetadataService\", grpc_method=\"Get\"}[${window}])) ",
       "legendFormat": "QPS"
      }
     ]
    },
    {
     "title": "Raft Proposals",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 667 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_raft_proposals{region=\"${region}\",  namespace=\"${namespace}\"}[${window}])) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "RangeCache Hit Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 675 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_raft_rangecache_lookups{rangecache_event_type=\"hit\", region=\"${region}\", namespace=\"${namespace}\"}[${window}]))/sum(rate(buildbuddy_raft_rangecache_lookups{region=\"${region}\",  namespace=\"${namespace}\"}[${window}]))"
      }
     ]
    },
    {
     "title": "Metarange RangeLease",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 675 },
     "targets": [
      {
       "expr": "max by (pod_name)(buildbuddy_raft_leases{region=\"${region}\", namespace=\"${namespace}\", range_id=\"1\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Metarange Leader",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 683 },
     "targets": [
      {
       "expr": "max by (pod_name, replicaid)(dragonboat_raftnode_has_leader{namespace=\"${namespace}\",region=\"${region}\", shardid=\"1\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC (MetadataService)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "gRPC server handling duration, q=${quantile}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1494 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(${quantile}, sum by (le, grpc_service, grpc_method) (rate(grpc_server_handling_seconds_bucket{region=\"${region}\", job=\"metadata-server\", grpc_service=\"metadata.service.MetadataService\", namespace=\"${namespace}\"})[$window]))",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Handled gRPC requests per second by method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1494 },
     "targets": [
      {
       "expr": "sum by (grpc_service, grpc_method) (rate(grpc_server_handled_total{job=\"metadata-server\", grpc_service=\"metadata.service.MetadataService\", namespace=\"${namespace}\"}[${window}]))",
       "legendFormat": "{{grpc_service}}.{{grpc_method}} {{pod_name}}"
      }
     ]
    },
    {
     "title": "Handled gRPC requests per second by status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1596 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (grpc_code) (rate(grpc_server_handled_total{region=\"${region}\", grpc_service=\"metadata.service.MetadataService\", namespace=\"${namespace}\"}[${window}]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC (RaftService)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "gRPC server handling duration, q=${quantile}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1503 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(${quantile}, sum by (le, grpc_service, grpc_method) (rate(grpc_server_handling_seconds_bucket{region=\"${region}\", job=\"metadata-server\", grpc_service=\"raft.service.Api\", namespace=\"${namespace}\"})[$window]))",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Handled gRPC requests per second by method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1503 },
     "targets": [
      {
       "expr": "sum by (grpc_service, grpc_method, pod_name) (rate(grpc_server_handled_total{job=\"metadata-server\", grpc_service=\"raft.service.Api\", namespace=\"${namespace}\"}[${window}]))",
       "legendFormat": "{{grpc_service}}.{{grpc_method}} {{pod_name}}"
      }
     ]
    },
    {
     "title": "Handled gRPC requests per second by status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1581 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (grpc_code) (rate(grpc_server_handled_total{region=\"${region}\", grpc_service=\"raft.service.Api\", namespace=\"${namespace}\"}[${window}]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "replica.Update latency (q=${quantile})",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 758 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(${quantile}, sum(rate(buildbuddy_raft_replica_update_duration_usec_bucket{region=\"${region}\", namespace=\"${namespace}\"}[${window}])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "range lock latency (q=${quantile})",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 758 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(${quantile}, sum(rate(buildbuddy_raft_range_lock_duration_msec_bucket{region=\"${region}\", namespace=\"${namespace}\"}[${window}])) by (pod_name, le))",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "nodehost.SyncPropose latency (q=${quantile})",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 806 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(${quantile}, sum(rate(buildbuddy_raft_nodehost_method_usec_bucket{region=\"${region}\", nodehost_method=\"SyncPropose\", namespace=\"${namespace}\"}[${window}])) by (pod_name, le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "nodehost.SyncPropose requests per sec by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 806 },
     "targets": [
      {
       "expr": "sum by (pod_name) (rate(buildbuddy_raft_nodehost_method_usec_count{job=\"metadata-server\",nodehost_method=\"SyncPropose\", namespace=\"${namespace}\"}[${window}]))",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "nodehost.SyncPropose errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 814 },
     "targets": [
      {
       "expr": "sum(increase(buildbuddy_raft_nodehost_method_errors{region=\"${region}\", job=\"metadata-server\", nodehost_method=\"SyncPropose\", namespace=\"${namespace}\"}[${window}])) by (dragonboat_error)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "nodehost.SyncPropose requests per sec by range",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 814 },
     "targets": [
      {
       "expr": "avg(sum by (range_id) (rate(buildbuddy_raft_nodehost_method_usec_count{job=\"metadata-server\",nodehost_method=\"SyncPropose\", namespace=\"${namespace}\", range_id!=\"1\"}[${window}])))",
       "legendFormat": "avg"
      },
      {
       "expr": "max(sum by (range_id) (rate(buildbuddy_raft_nodehost_method_usec_count{job=\"metadata-server\",nodehost_method=\"SyncPropose\", namespace=\"${namespace}\", range_id!=\"1\"}[${window}])))",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Partition Operations By Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum(increase(buildbuddy_raft_partition_operations{region=\"${region}\", namespace=\"${namespace}\"}[${window}]))by(op, status)",
       "legendFormat": "{{op}}, {{status}}"
      }
     ]
    },
    {
     "title": "Number of Ranges Per Partition",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "count by (partition_id) (\n    count by (partition_id, range_id) (buildbuddy_raft_range_replica{region=\"$region\", namespace=\"$namespace\"})\n  )\n",
       "legendFormat": "{{partition_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transaction Records",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum (increase(buildbuddy_raft_txn_record_process_count{region=\"${region}\", namespace=\"${namespace}\"}[$window])) by (txn_record_process_status)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Range and Leases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raft Ranges",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "count(count by (range_id)(buildbuddy_raft_bytes{region=\"${region}\", namespace=\"${namespace}\"}) )",
       "legendFormat": "total"
      },
      {
       "expr": "avg(buildbuddy_raft_ranges{region=\"${region}\", namespace=\"${namespace}\"}) by (node_host_id, pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Lease Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum(buildbuddy_raft_leases{region=\"${region}\", namespace=\"${namespace}\"}) by (node_host_id, pod_name)",
       "legendFormat": "{{pod_name}} - {{node_host_id}}"
      }
     ]
    },
    {
     "title": "Number of ranges not in 3 zones",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "count(\n    count by (range_id) (\n      count by (range_id, zone) (buildbuddy_raft_range_replica{region=\"$region\", namespace=\"$namespace\"})\n    ) != 3\n  ) or vector(0)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of ranges w/o leases",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum (count_eq_over_time(max by (range_id) (buildbuddy_raft_leases{region=\"${region}\", namespace=\"${namespace}\"}), 0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Range Sizes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "avg(buildbuddy_raft_bytes{region=\"${region}\", namespace=\"${namespace}\"})/1e6",
       "legendFormat": "avg"
      },
      {
       "expr": "max(buildbuddy_raft_bytes{region=\"${region}\", namespace=\"${namespace}\"})/1e6",
       "legendFormat": "max"
      },
      {
       "expr": "avg(buildbuddy_raft_bytes{region=\"${region}\", namespace=\"${namespace}\"}/1e6) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Lease Action Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "sum(increase(buildbuddy_raft_lease_action_count{region=\"${region}\", status!=\"OK\"}[${window}])) by (pod_name,lease_action, range_id)",
       "legendFormat": "{{pod_name}} - {{lease_action}} - {{range_id}}"
      }
     ]
    },
    {
     "title": "Lease Acquisition latency (q=${quantile})",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(${quantile}, sum(rate(buildbuddy_raft_lease_action_duration_msec_bucket{region=\"${region}\", namespace=\"${namespace}\", lease_action=\"Acquire\"}[${window}])) by (pod_name, le))",
       "legendFormat": "{{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Splits & Moves",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Driver Actions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(increase(buildbuddy_raft_driver_actions{region=\"${region}\", namespace=\"${namespace}\"}[${window}])) by (driver_action)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Raft Moves",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(increase(buildbuddy_raft_moves{region=\"${region}\", namespace=\"${namespace}\"}[${window}])) by (move_type, status)",
       "legendFormat": "{{move_type}}: {{status}}"
      }
     ]
    },
    {
     "title": "Raft Splits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum (increase(buildbuddy_raft_splits{region=\"${region}\", namespace=\"${namespace}\"}[${window}])) by (pod_name, status)",
       "legendFormat": "{{status}}: {{pod_name}}"
      }
     ]
    },
    {
     "title": "Split Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(buildbuddy_raft_split_duration_usec_bucket{region=\"${region}\", namespace=\"${namespace}\"}[${window}])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(buildbuddy_raft_split_duration_usec_bucket{region=\"${region}\", namespace=\"${namespace}\"}[${window}])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(buildbuddy_raft_split_duration_usec_bucket{region=\"${region}\"}[${window}])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Intermediate Replicas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum(buildbuddy_raft_intermediate_replicas_count{region=\"${region}\", namespace=\"${namespace}\"}) by (replica_state, range_id)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raft Store Events Chan Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2192 },
     "targets": [
      {
       "expr": "sum by (pod_name) (buildbuddy_raft_store_events{region=\"${region}\", namespace=\"${namespace}\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Raft Store Broadcast Events Dropped ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2192 },
     "targets": [
      {
       "expr": "sum by (pod_name, raft_event, event_broadcast_source) (buildbuddy_raft_store_event_broadcast_dropped{region=\"${region}\", namespace=\"${namespace}\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Raft Listener Events Dropped",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2246 },
     "targets": [
      {
       "expr": "sum by (listener_event, listener_id) (buildbuddy_raft_listener_events_dropped{region=\"${region}\", namespace=\"${namespace}\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Raft Store Listener Events Dropped ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2246 },
     "targets": [
      {
       "expr": "sum by (raft_event, listener_id) (buildbuddy_raft_store_event_listener_dropped{region=\"${region}\", namespace=\"${namespace}\"})",
       "legendFormat": "{{listener_id}}: {{raft_event}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Zombies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Zombies",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3749 },
     "targets": [
      {
       "expr": "sum (buildbuddy_raft_zombie_cleanup_tasks{region=\"${region}\", namespace=\"${namespace}\"}) by (pod_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Zombie Cleanup Errors by Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3749 },
     "targets": [
      {
       "expr": "sum(increase(buildbuddy_raft_zombie_cleanup{region=\"${region}\", namespace=\"${namespace}\"}[${window}])) by (pod_name,status)",
       "legendFormat": "{{pod_name}} - {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Golang",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2804 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (go_memstats_heap_alloc_bytes{region=\"${region}\", job=\"metadata-server\", namespace=\"${namespace}\"}) by (job, pod_name, namespace)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Next GC heap size",
     "type": "timeseries",
     "description": "Size of the heap when the next GC will start",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2804 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum (go_memstats_next_gc_bytes{region=\"${region}\", job=\"metadata-server\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Time since last GC",
     "type": "timeseries",
     "description": "Time passed since the last GC finished. Smaller times indicate that the GC is running more frequently.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2956 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg_over_time((time() - sum by (pod_name)(go_memstats_last_gc_time_seconds{region=\"${region}\", job=\"metadata-server\"}))[$__rate_interval])",
       "legendFormat": "{{job}} @ {{pod_name}}, {{namespace}}"
      }
     ]
    },
    {
     "title": "Median GC duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2956 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum (go_gc_duration_seconds{region=\"${region}\", quantile=\"0.5\",job=\"metadata-server\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3084 },
     "targets": [
      {
       "expr": "sum (go_goroutines{region=\"${region}\", job=\"metadata-server\"} ) by (pod_name)",
       "legendFormat": "{{job}} @ {{pod_name}}, {{namespace}}"
      }
     ]
    },
    {
     "title": "OS threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3084 },
     "targets": [
      {
       "expr": "sum (go_threads{region=\"${region}\", job=\"metadata-server\"} ) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dragonboat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Num of Shards",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1321 },
     "targets": [
      {
       "expr": "count(max by (shardid)(dragonboat_raftnode_has_leader{namespace=\"${namespace}\",region=\"${region}\"}))",
       "legendFormat": "Total number of shards w/ a leader"
      }
     ]
    },
    {
     "title": "Num of Shards w/o Leader",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1321 },
     "targets": [
      {
       "expr": "sum(count_eq_over_time(max by (shardid)(dragonboat_raftnode_has_leader{namespace=\"${namespace}\",region=\"${region}\"}), 0))",
       "legendFormat": "Total number of shards w/o a leader"
      }
     ]
    },
    {
     "title": "Proposal Dropped",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1329 },
     "targets": [
      {
       "expr": "sum by (pod_name) (increase(dragonboat_raftnode_proposal_dropped_total{namespace=\"${namespace}\", region=\"${region}\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of shards with less than 3 shards",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1329 },
     "targets": [
      {
       "expr": "min_over_time(count( count by (shardid)(dragonboat_raftnode_has_leader{namespace=\"${namespace}\",region=\"${region}\"}) < 3)[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Dragonboat Transport",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed Message Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4238 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod_name)(increase(dragonboat_transport_failed_message_connection_attempt_total{namespace=\"${namespace}\", region=\"${region}\"}[${window}]))",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Received Message Dropped",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4238 },
     "targets": [
      {
       "expr": "sum by (pod_name)(increase(dragonboat_transport_received_message_dropped_total{namespace=\"${namespace}\", region=\"${region}\"}[${window}]))",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Message Send Failure Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4246 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (pod_name)(increase(dragonboat_transport_message_send_failure_total{namespace=\"${namespace}\", region=\"${region}\"}[${window}]) / (increase(dragonboat_transport_message_send_failure_total{namespace=\"${namespace}\", region=\"${region}\"}[${window}]) + increase(dragonboat_transport_message_send_success_total{namespace=\"${namespace}\", region=\"${region}\"}[${window}])))",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Received Message",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4246 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod_name)(increase(dragonboat_transport_received_message_total{namespace=\"${namespace}\", region=\"${region}\"}[${window}]))",
       "legendFormat": "{{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pebble",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "block cache size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2961 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod_name) (buildbuddy_remote_cache_pebble_cache_pebble_block_cache_size_bytes{region=\"${region}\", job=\"metadata-server\"})",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "block cache hits and misses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2961 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (cache_status) (rate(buildbuddy_remote_cache_pebble_cache_pebble_block_cache_requests_count{region=\"${region}\", job=\"metadata-server\"}[${window}]))",
       "legendFormat": "{{cache_status}}"
      },
      {
       "expr": "sum(rate(buildbuddy_remote_cache_pebble_cache_pebble_block_cache_requests_count{region=\"${region}\", job=\"metadata-server\", cache_status=\"hit\"}[${window}])) / sum(rate(buildbuddy_remote_cache_pebble_cache_pebble_block_cache_requests_count{region=\"${region}\", job=\"metadata-server\"}[${window}]))",
       "legendFormat": "hit_ratio"
      }
     ]
    },
    {
     "title": "Compaction rate  (by type)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2969 },
     "repeat": "cache_name",
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_cache_pebble_cache_pebble_compact_count{region=\"${region}\", cache_name=\"raft\", namespace=\"${namespace}\"}[1m])) by (compaction_type)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Compaction state",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 12, "y": 2969 },
     "repeat": "cache_name",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(buildbuddy_remote_cache_pebble_cache_pebble_compact_in_progress_bytes{region=\"${region}\",cache_name=\"raft\", namespace=\"${namespace}\"})",
       "legendFormat": "in progress (bytes)"
      },
      {
       "expr": "sum(buildbuddy_remote_cache_pebble_cache_pebble_compact_in_progress{region=\"${region}\",cache_name=\"raft\", namespace=\"${namespace}\"})",
       "legendFormat": "in progress (count)"
      },
      {
       "expr": "sum(buildbuddy_remote_cache_pebble_cache_pebble_compact_marked_files{region=\"${region}\",cache_name=\"raft\", namespace=\"${namespace}\"})",
       "legendFormat": "marked files"
      }
     ]
    },
    {
     "title": "Compaction estimated debt",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2977 },
     "repeat": "cache_name",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(buildbuddy_remote_cache_pebble_cache_pebble_compact_estimated_debt_bytes{region=\"${region}\", cache_name=\"raft\", namespace=\"${namespace}\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Op Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 12, "y": 2977 },
     "repeat": "cache_name",
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_cache_pebble_cache_pebble_op_count{region=\"${region}\", pebble_id=\"raft_store\", namespace=\"${namespace}\"}[1m])) by (pebble_op)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Op p50 Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2985 },
     "repeat": "cache_name",
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(buildbuddy_remote_cache_pebble_cache_pebble_op_latency_usec_bucket{region=\"${region}\", pebble_id=\"raft_store\", namespace=\"${namespace}\"}[1m])) by (le,pebble_op))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Op p95 Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 12, "y": 2985 },
     "repeat": "cache_name",
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(buildbuddy_remote_cache_pebble_cache_pebble_op_latency_usec_bucket{region=\"${region}\", pebble_id=\"raft_store\", namespace=\"${namespace}\"}[1m])) by (le,pebble_op))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Op p99 Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2994 },
     "repeat": "cache_name",
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(buildbuddy_remote_cache_pebble_cache_pebble_op_latency_usec_bucket{region=\"${region}\", pebble_id=\"raft_store\", namespace=\"${namespace}\"}[1m])) by (le,pebble_op))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Zombie Table Size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2994 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(buildbuddy_remote_cache_pebble_cache_zombie_table_size_bytes{region=\"${region}\", namespace=\"${namespace}\"}) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Zombie Table Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3003 },
     "targets": [
      {
       "expr": "sum(buildbuddy_remote_cache_pebble_cache_zombie_table_count{region=\"${region}\", namespace=\"${namespace}\"}) ",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Pebble Levels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number files (by level)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2299 },
     "targets": [
      {
       "expr": "sum(buildbuddy_remote_cache_pebble_cache_pebble_level_num_files{region=\"${region}\", cache_name=\"raft\", namespace=\"${namespace}\"}) by (level)",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Size (by level)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2299 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(buildbuddy_remote_cache_pebble_cache_pebble_level_size_bytes{region=\"${region}\", cache_name=\"raft\", namespace=\"${namespace}\"}) by (level)",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Compaction score (by level)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2491 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(buildbuddy_remote_cache_pebble_cache_pebble_level_score{region=\"${region}\", cache_name=\"raft\", namespace=\"${namespace}\"}) by (level)",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Bytes in (by level)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2491 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_cache_pebble_cache_pebble_level_bytes_in_count{region=\"${region}\", cache_name=\"raft\", namespace=\"${namespace}\"}[1m])) by (level)",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Bytes ingested (by level)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2499 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_cache_pebble_cache_pebble_level_bytes_ingested_count{region=\"${region}\", cache_name=\"raft\", namespace=\"${namespace}\"}[1m])) by (level)",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Bytes moved (by level)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2499 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_cache_pebble_cache_pebble_level_bytes_moved_count{region=\"${region}\", cache_name=\"raft\", namespace=\"${namespace}\"}[1m])) by (level)",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Bytes read (by level)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2507 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_cache_pebble_cache_pebble_level_bytes_read_count{region=\"${region}\", cache_name=\"raft\", namespace=\"${namespace}\"}[1m])) by (level)",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Bytes compacted (by level)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2507 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_cache_pebble_cache_pebble_level_bytes_compacted_count{region=\"${region}\", cache_name=\"raft\"}[1m])) by (level)",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Bytes flushed (by level)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2515 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_cache_pebble_cache_pebble_level_bytes_flushed_count{region=\"${region}\", cache_name=\"raft\"}[1m])) by (level)",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Tables compacted (by level)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2515 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_cache_pebble_cache_pebble_level_tables_compacted_count{region=\"${region}\", cache_name=\"raft\", namespace=\"${namespace}\"}[1m])) by (level)",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Tables flushed (by level)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2523 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_cache_pebble_cache_pebble_level_tables_flushed_count{region=\"${region}\", cache_name=\"raft\", namespace=\"${namespace}\"}[1m])) by (level)",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Tables ingested (by level)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2523 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_cache_pebble_cache_pebble_level_tables_ingested_count{region=\"${region}\", cache_name=\"raft\", namespace=\"${namespace}\"}[1m])) by (level)",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Tables moved (by level)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2531 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(buildbuddy_remote_cache_pebble_cache_pebble_level_tables_moved_count{region=\"${region}\", cache_name=\"raft\", namespace=\"${namespace}\"}[1m])) by (level)",
       "legendFormat": "{{level}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Eviction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Cache Filesystem Usage ",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 490 },
     "repeat": "cache_name",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max((buildbuddy_remote_cache_disk_cache_filesystem_total_bytes{region=\"${region}\", cache_name=\"raft\", namespace=\"${namespace}\"}-buildbuddy_remote_cache_disk_cache_filesystem_avail_bytes{region=\"${region}\",cache_name=\"raft\", namespace=\"${namespace}\"})/buildbuddy_remote_cache_disk_cache_filesystem_total_bytes{region=\"${region}\", cache_name=\"raft\", namespace=\"${namespace}\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Disk Cache Partition Usage ",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 12, "y": 490 },
     "repeat": "cache_name",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(buildbuddy_remote_cache_disk_cache_partition_size_bytes{region=\"${region}\",cache_name=\"raft\", namespace=\"${namespace}\"})by (partition_id)/max(buildbuddy_remote_cache_disk_cache_partition_capacity_bytes{region=\"${region}\", cache_name=\"raft\", namespace=\"${namespace}\"}) by (partition_id)",
       "legendFormat": " {{partition_id}}"
      },
      {
       "expr": "sum(buildbuddy_remote_cache_disk_cache_partition_size_bytes{region=\"${region}\",cache_name=\"raft\", namespace=\"${namespace}\"}) by (pod_name, partition_id)",
       "legendFormat": "{{pod_name}} {{partition_id}}"
      }
     ]
    },
    {
     "title": "Raft Eviction errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 501 },
     "targets": [
      {
       "expr": "sum(increase(buildbuddy_raft_eviction_errors{region=\"${region}\", namespace=\"${namespace}\"}[${window}]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Eviction sample queue length",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 501 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(buildbuddy_raft_eviction_samples_chan_size{region=\"${region}\", job=\"metadata-server\"}[${window}]) by (partition_id)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Eviction resample latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 510 },
     "repeat": "cache_name",
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(${quantile}, sum(rate(buildbuddy_remote_cache_pebble_cache_eviction_resample_latency_usec_bucket{region=\"${region}\", cache_name=\"raft\", namespace=\"${namespace}\"}[${window}])) by (le, partition_id))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Eviction evict latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 12, "y": 510 },
     "repeat": "cache_name",
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(${quantile}, sum(rate(buildbuddy_remote_cache_pebble_cache_eviction_evict_latency_usec_bucket{region=\"${region}\", cache_name=\"raft\", namespace=\"${namespace}\"}[${window}])) by (le, partition_id))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Cache Avg Last Evicted Age ",
     "type": "timeseries",
     "description": "Avg age of last item evicted",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 520 },
     "repeat": "cache_name",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(buildbuddy_remote_cache_disk_cache_last_eviction_age_usec{region=\"${region}\", cache_name=\"raft\", namespace=\"${namespace}\"}/1e6) by (partition_id)"
      }
     ]
    },
    {
     "title": "Eviction Age ($partition_id)",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 12, "y": 520 },
     "repeat": "cache_name",
     "targets": [
      {
       "expr": "sum(increase(buildbuddy_remote_cache_disk_cache_eviction_age_msec_bucket{region=\"$region\", partition_id=\"$partition_id\", cache_name=\"raft\", namespace=\"${namespace}\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Disk Cache eviction rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 530 },
     "repeat": "cache_name",
     "targets": [
      {
       "expr": "max(rate(buildbuddy_remote_cache_disk_cache_num_evictions{region=\"${region}\",cache_name=\"raft\", namespace=\"${namespace}\"}[10m])) by (pod_name, partition_id)",
       "legendFormat": "{{partition_id}} {{pod_name}}"
      }
     ]
    },
    {
     "title": "batch delete latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 530 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(buildbuddy_raft_batch_delete_usec_bucket{region=\"${region}\", job=\"metadata-server\", namespace=\"${namespace}\"})[$window]))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(buildbuddy_raft_batch_delete_usec_bucket{region=\"${region}\", job=\"metadata-server\", namespace=\"${namespace}\"})[$window]))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(buildbuddy_raft_batch_delete_usec_bucket{region=\"${region}\", job=\"metadata-server\", namespace=\"${namespace}\"})[$window]))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "# gcs deletes dropped",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 539 },
     "targets": [
      {
       "expr": "sum by (partition_id)(buildbuddy_raft_gcs_delete_dropped{region=\"${region}\", namespace=\"${namespace}\"})",
       "legendFormat": "{{partition_id}}"
      }
     ]
    },
    {
     "title": "GCS Eviction queue length",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 539 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(buildbuddy_raft_eviction_gcs_chan_size{region=\"${region}\", job=\"metadata-server\"}[${window}]) by (partition_id)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "# gcs delete",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 547 },
     "targets": [
      {
       "expr": "sum by (status)(rate(buildbuddy_raft_gcs_eviction_count{region=\"${region}\", namespace=\"${namespace}\"}[$window]))",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ATime Update",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "# gcs atime update",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 667 },
     "targets": [
      {
       "expr": "sum by (status)(rate(buildbuddy_raft_atime_update_gcs_count{region=\"${region}\", namespace=\"${namespace}\"}[$window]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "batch atime update latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 667 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(buildbuddy_raft_batch_atime_update_usec_bucket{region=\"${region}\", job=\"metadata-server\", namespace=\"${namespace}\"})[$window]))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(buildbuddy_raft_batch_atime_update_usec_bucket{region=\"${region}\", job=\"metadata-server\", namespace=\"${namespace}\"})[$window]))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(buildbuddy_raft_batch_atime_update_usec_bucket{region=\"${region}\", job=\"metadata-server\", namespace=\"${namespace}\"})[$window]))",
       "legendFormat": "p50"
      }
     ]
    }
   ]
  }
 ]
}