{
 "title": "BuildBuddy Remote Execution Performance",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "workload",
    "query": "label_values(rbeperf_remote_stats_millis, workload)"
   },
   {
    "name": "percentile",
    "query": "label_values(rbeperf_remote_stats_millis, percentile)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rbeperf_remote_stats_millis{percentile=\"$percentile\",workload=\"$workload\",stage=\"total\"}"
    },
    {
     "expr": "rbeperf_local_stats_millis{percentile=\"$percentile\",workload=\"$workload\",stage=\"total\"}"
    }
   ]
  },
  {
   "title": "Remote By Stage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rbeperf_remote_stats_millis{percentile=\"$percentile\",workload=\"$workload\",stage!=\"total\"}"
    }
   ]
  },
  {
   "title": "Local By Stage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rbeperf_local_stats_millis{percentile=\"$percentile\",workload=\"$workload\",stage!=\"total\"}"
    }
   ]
  },
  {
   "title": "Perf Runner Diagnostics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rbeperf_last_successful_run{workload=\"$workload\"}",
     "legendFormat": "Last Successful Run"
    },
    {
     "expr": "rbeperf_num_failed_commands{workload=\"$workload\"}",
     "legendFormat": "Number Failed Commands"
    }
   ]
  }
 ]
}