{
 "title": "Workflow Snapshotting",
 "tags": [ "file:workflow.json" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "region", "query": { "query": "label_values(up,region)" } }
  ]
 },
 "panels": [
  {
   "title": "Remote runner workloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": " sum by (op, os, arch, self_hosted, stage) (\n    increase(buildbuddy_remote_runner_requests{}[5m])\n  )",
     "legendFormat": "{{op}} {{stage}} (self-hosted={{self_hosted}}, {{os}}-{{arch}})"
    }
   ]
  },
  {
   "title": "Retry rate (Linux)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": " 100 *\n  sum by (op) (\n    rate(buildbuddy_remote_runner_requests{stage=\"retry\", os=\"linux\", arch=\"amd64\", self_hosted=\"false\"}[5m])\n  )\n  /\n  clamp_min(\n    sum by (op) (\n      rate(buildbuddy_remote_runner_requests{stage=\"initial\", os=\"linux\", arch=\"amd64\", self_hosted=\"false\"}[5m])\n    ),\n    0.001\n  )\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top groups (Linux)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(\n    10,\n    sum by (group_id) (\n      increase(buildbuddy_remote_runner_requests{stage=\"initial\", self_hosted=\"false\", os=\"linux\"}[1h])\n    )\n  )\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution errors",
   "type": "timeseries",
   "description": "The number of Firecracker execution errors, labeled by reason.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (reason, job)(increase(buildbuddy_firecracker_execution_error_count{job=~\"executor-workflows.*\", region=~\"$region\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshot bytes read per source",
   "type": "timeseries",
   "description": "The number of snapshot bytes read from each source. These are uncompressed values, even if the data was compressed in the cache.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (file_name, chunk_source) (rate(buildbuddy_firecracker_cow_snapshot_bytes_read{region=~\"$region\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Stage P95 Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\n\t  0.95,\n\t  sum by(le, stage) (\n\t     rate(buildbuddy_firecracker_stage_duration_usec_bucket{region=~\"$region\", job=~\"executor-workflows.*\"}[10m])\n\t    )\n) / 1e6 / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warm Workflow Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "(sum(rate(buildbuddy_remote_execution_recycle_runner_requests{region=~\"$region\", job=~\"executor-workflows.*\", status=\"hit\"}[60m])) * 60 * 60)\n/\n((sum(rate(buildbuddy_remote_execution_recycle_runner_requests{region=~\"$region\", job=~\"executor-workflows.*\"}[60m])) > 0)* 60 * 60 > 10)",
     "legendFormat": "runner reuse rate (1h window, where at least 10 workflows executed)"
    },
    {
     "expr": "clamp_max(\n  sum(\n    (up{region=~\"$region\", job=~\"executor-workflows.*\"} offset 3m)\n      unless\n     up{region=~\"$region\", job=~\"executor-workflows.*\"}\n  )\n    /\n  sum(up{region=~\"$region\", job=~\"executor-workflows.*\"}),\n1)",
     "legendFormat": "event: fraction of executors shutdown (approx)"
    },
    {}
   ]
  },
  {
   "title": "Rootfs Dirty Chunk Ratio",
   "type": "heatmap",
   "description": "After a copy-on-write rootfs file has been used, the ratio of dirty/total chunks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(buildbuddy_firecracker_cow_snapshot_dirty_chunk_ratio_bucket{region=~\"$region\", file_name=\"rootfs\", job=~\"executor-workflows.*\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Memory Snapshot Dirty Chunk Ratio",
   "type": "heatmap",
   "description": "After a copy-on-write memory snapshot has been used, the ratio of dirty/total chunks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(increase(buildbuddy_firecracker_cow_snapshot_dirty_chunk_ratio_bucket{region=~\"$region\", file_name=\"memory\", job=~\"executor-workflows.*\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Local snapshot bytes written",
   "type": "timeseries",
   "description": "The number of uncompressed snapshot bytes written to the local cache. This will be 0 if the artifact was already cached.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(increase(buildbuddy_remote_execution_file_cache_added_file_size_bytes_sum{region=~\"$region\", job=~\"executor-workflows.*\"}[5m])) / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remote snapshot bytes written (Compressed)",
   "type": "timeseries",
   "description": "The number of compressed snapshot bytes written to the remote cache. This will be 0 if the artifact was already cached.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (file_name) (rate(buildbuddy_firecracker_snapshot_remote_cache_upload_size_bytes{region=~\"$region\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory-mapped bytes (current)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod_name) (buildbuddy_firecracker_cow_snapshot_memory_mapped_bytes{region=~\"$region\", job=~\"executor-workflows.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshot bytes read per source",
   "type": "timeseries",
   "description": "The number of snapshot bytes read from each source. These are uncompressed values, even if the data was compressed in the cache.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (file_name, chunk_source) (rate(buildbuddy_firecracker_cow_snapshot_bytes_read{region=~\"$region\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File cache operation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": " histogram_quantile(0.95, \n    sum by(le, op) (\n      rate(buildbuddy_remote_execution_file_cache_op_latency_usec_bucket{region=~\"$region\", job=~\"executor-workflows.*\"}[5m])\n    )\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of Unmapped Snapshot Chunks",
   "type": "heatmap",
   "description": "The count represents the number of workflows where X% of snapshot chunks were not dynamically initialized during execution. Filter by `file_name` for more granularity between `memory` and `rootfs` snapshots.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(increase(buildbuddy_firecracker_cow_snapshot_chunk_source_ratio_bucket{region=~\"$region\", job=~\"executor-workflows.*\", chunk_source=\"unmapped\"}[5m])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Dial VM Exec Server Duration (Sec) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "histogram_quantile(\n\t  0.95,\n\t  sum by(le) (\n\t     rate(buildbuddy_firecracker_exec_dial_duration_usec_bucket{region=~\"$region\"}[3m])\n\t    )\n) / 1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Init Snapshot Operation Durations (sec)",
   "type": "timeseries",
   "description": "Total time spent on each operation during VM initialization (everything before a command can be executed in the VM)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "histogram_quantile(\n\t  0.95,\n\t  sum by(le, file_name, name) (\n\t     rate(buildbuddy_firecracker_cow_snapshot_chunk_operation_duration_usec_bucket{region=~\"$region\"}[3m])\n\t    )\n) / 1e6",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n     0.95,\n     sum by(le, stage) (\n        rate(buildbuddy_firecracker_cow_snapshot_page_fault_total_duration_usec_bucket{region=~\"$region\"}[3m])\n       )\n) / 1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of Chunks Fetched from Remote Cache",
   "type": "heatmap",
   "description": "The count represents the number of workflows where X% of snapshot chunks were fetched from the remote cache. Filter by `file_name` for more granularity between `memory` and `rootfs` snapshots.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "sum(increase(buildbuddy_firecracker_cow_snapshot_chunk_source_ratio_bucket{region=~\"$region\", job=~\"executor-workflows.*\", chunk_source=\"remote_cache\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Snapshot Save Workloads",
   "type": "timeseries",
   "description": "The number of snapshot save workloads currently executing.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum by(stage) (buildbuddy_firecracker_snapshot_save_workloads_executing{region=\"$region\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of Chunks Fetched from Local Filecache",
   "type": "heatmap",
   "description": "The count represents the number of workflows where X% of snapshot chunks were fetched from the local filecache. Filter by `file_name` for more granularity between `memory` and `rootfs` snapshots.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "sum(increase(buildbuddy_firecracker_cow_snapshot_chunk_source_ratio_bucket{region=~\"$region\",  job=~\"executor-workflows.*\", chunk_source=\"local_filecache\"}[5m])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}