load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "scratchspace",
    srcs = ["scratchspace.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/scratchspace",
    visibility = ["//visibility:public"],
    deps = ["//server/util/status"],
)
