load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "changelogtags",
    srcs = ["changelogtags.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/tools/lint/changelogtags",
    visibility = ["//tools/lint:__pkg__"],
    deps = ["//tools/lint/util"],
)
