load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "schema",
    srcs = ["schema.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/codesearch/schema",
    visibility = ["//visibility:public"],
    deps = [
        "//codesearch/types"
    ],
)
