load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "metricsutil",
    srcs = ["metricsutil.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/metricsutil",
    visibility = ["//visibility:public"],
    deps = [
        "//server/util/flag",
    ],
)
