load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "subdomain",
    srcs = ["subdomain.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/subdomain",
    visibility = ["//visibility:public"],
    deps = ["//server/util/flagutil"],
)
