load("//rules/typescript:index.bzl", "ts_library")

ts_library(
    name = "cta",
    srcs = ["cta.tsx"],
    deps = [
        "//website/src/components/cta:cta.module.css",
        "//website/src/css:common.module.css",
        "@npm//@types/react",
        "@npm//react",
    ],
)
