load("//rules/typescript:index.bzl", "ts_library")

ts_library(
    name = "quote",
    srcs = ["quote.tsx"],
    deps = [
        "//website/src/components/quote:quote.module.css",
        "//website/src/css:common.module.css",
        "@npm//@types/react",
        "@npm//react",
    ],
)
