load("//rules/typescript:index.bzl", "ts_library")

package(default_visibility = ["//visibility:public"])

ts_library(
    name = "github",
    srcs = ["github.tsx"],
    deps = [
        "@npm//@types/react",
        "@npm//react",
    ],
)

ts_library(
    name = "google",
    srcs = ["google.tsx"],
    deps = [
        "@npm//@types/react",
        "@npm//react",
    ],
)
