load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "current_request",
    srcs = ["current_request.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/current_request",
    visibility = ["//visibility:public"],
)
