load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "testport",
    srcs = ["testport.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/testutil/testport",
    visibility = ["//visibility:public"],
)
