load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "logging",
    srcs = ["logging.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/cli/logging",
    visibility = ["//visibility:public"],
)
