load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "signalutil",
    srcs = ["signalutil.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/signalutil",
    visibility = ["//visibility:public"],
)
