load("//rules/typescript:index.bzl", "ts_library")

ts_library(
    name = "databuddy_ts_proto",
    srcs = ["databuddy_ts_proto.d.ts"],
    deps = [
        "@npm//@types/long",
        "@npm//long",
        "@npm//protobufjs",
        "@npm//tslib",
    ],
)
