name: "Restore download caches"
description: "Restores external dependencies caches, and outputs cache-hit statuses."
inputs:
  repo-cache-dir:
    description: "The directory where the Bazel Repo cache is stored."
    required: true
    default: "$HOME/repo-cache"
  go-mod-cache-dir:
    description: "The directory where the Go Mod cache is stored."
    required: true
    default: "$HOME/go-mod-cache"
  yarn-cache-dir:
    description: "The directory where the Yarn cache is stored."
    required: true
    default: "$HOME/.cache/yarn/v6"
outputs:
  repo-cache-hit:
    description: "Cache hit status for Bazel Repo Cache"
    value: ${{ steps.repo-cache-restore.outputs.cache-hit }}
  go-mod-cache-hit:
    description: "Cache hit status for Go Mod Cache"
    value: ${{ steps.go-mod-cache-restore.outputs.cache-hit }}
  yarn-cache-hit:
    description: "Cache hit status for Yarn Cache"
    value: ${{ steps.yarn-cache-restore.outputs.cache-hit }}
runs:
  using: composite
  # Github Actions does not allow overwriting an existing cache key.
  # So we write a new cache key for each run attempt, while restoring the cache with a prefix match.
  #
  # Reference: https://github.com/actions/cache/pull/1452
  steps:
    - name: Restore Bazel Repo Cache
      uses: actions/cache/restore@v4
      id: repo-cache-restore
      with:
        path: ${{ inputs.repo-cache-dir }}
        key: repo-cache-${{ runner.os }}-${{ hashFiles('MODULE.bazel', 'WORKSPACE.bzlmod', 'WORKSPACE', 'deps.bzl') }}-${{ github.run_id }}-${{ github.run_attempt }}
        restore-keys: |
          repo-cache-${{ runner.os }}-${{ hashFiles('MODULE.bazel', 'WORKSPACE.bzlmod', 'WORKSPACE', 'deps.bzl') }}-
          repo-cache-${{ runner.os }}-

    - name: Restore Go Mod Cache
      uses: actions/cache/restore@v4
      id: go-mod-cache-restore
      with:
        path: ${{ inputs.go-mod-cache-dir }}
        key: go-mod-cache-${{ runner.os }}-${{ hashFiles('MODULE.bazel', 'WORKSPACE.bzlmod', 'WORKSPACE', 'go.mod', 'go.sum', 'deps.bzl') }}-${{ github.run_id }}-${{ github.run_attempt }}
        restore-keys: |
          go-mod-cache-${{ runner.os }}-${{ hashFiles('MODULE.bazel', 'WORKSPACE.bzlmod', 'WORKSPACE', 'go.mod', 'go.sum', 'deps.bzl') }}-
          go-mod-cache-${{ runner.os }}-

    - name: Restore Yarn Cache
      uses: actions/cache/restore@v4
      id: yarn-cache-restore
      with:
        path: ${{ inputs.yarn-cache-dir }}
        key: yarn-cache-${{ runner.os }}-${{ hashFiles('**/yarn.lock', '**/package.json') }}-${{ github.run_id }}-${{ github.run_attempt }}
        restore-keys: |
          yarn-cache-${{ runner.os }}-${{ hashFiles('**/yarn.lock', '**/package.json') }}-
          yarn-cache-${{ runner.os }}-
