#!/usr/bin/env bash

# QA Test Runner for rules_bazel_integration_test
# This script downloads a source tarball, injects BuildBuddy toolchain,
# and runs Bazel commands against it using BuildBuddy RBE.

set -euo pipefail

# Get Bazel binary and workspace from rules_bazel_integration_test framework
bazel="${BIT_BAZEL_BINARY:-}"
workspace_dir="${BIT_WORKSPACE_DIR:-}"

# Get QA configuration from environment
tarball_url="${QA_TARBALL_URL:-}"
strip_prefix="${QA_STRIP_PREFIX:-}"
bazel_command="${QA_BAZEL_COMMAND:-}"
api_key="${BB_API_KEY:-}"

# Debug: Show all environment variables related to test
echo "DEBUG: Environment variables available:"
env | grep -E "(BB_|BIT_|QA_|TEST)" | head -20 || true

# Validate required environment variables
if [[ -z "${bazel}" ]]; then
  echo >&2 "ERROR: BIT_BAZEL_BINARY not set"
  exit 1
fi

if [[ -z "${workspace_dir}" ]]; then
  echo >&2 "ERROR: BIT_WORKSPACE_DIR not set"
  exit 1
fi

if [[ -z "${tarball_url}" ]]; then
  echo >&2 "ERROR: QA_TARBALL_URL not set"
  exit 1
fi

if [[ -z "${strip_prefix}" ]]; then
  echo >&2 "ERROR: QA_STRIP_PREFIX not set"
  exit 1
fi

if [[ -z "${bazel_command}" ]]; then
  echo >&2 "ERROR: QA_BAZEL_COMMAND not set"
  exit 1
fi

echo "=================================================="
echo "QA Integration Test Runner"
echo "=================================================="
echo "Bazel binary: ${bazel}"
echo "Workspace: ${workspace_dir}"
echo "Tarball URL: ${tarball_url}"
echo "Strip prefix: ${strip_prefix}"
echo "Bazel command: ${bazel_command}"
echo "=================================================="

# Change to workspace directory
cd "${workspace_dir}"

# Download tarball
echo "Downloading tarball from ${tarball_url}..."
if ! curl -L "${tarball_url}" -o repo.tar.gz; then
  echo >&2 "ERROR: Failed to download tarball from ${tarball_url}"
  exit 1
fi

# Extract tarball
echo "Extracting tarball..."
if ! tar -xzf repo.tar.gz; then
  echo >&2 "ERROR: Failed to extract tarball"
  exit 1
fi

# Change into extracted directory
if [[ ! -d "${strip_prefix}" ]]; then
  echo >&2 "ERROR: Expected directory ${strip_prefix} not found after extraction"
  ls -la
  exit 1
fi

cd "${strip_prefix}"
echo "Working directory: $(pwd)"

# Inject BuildBuddy toolchain (bzlmod only)
if [[ ! -f MODULE.bazel ]]; then
  echo >&2 "ERROR: No MODULE.bazel found. Only bzlmod projects are supported."
  exit 1
fi

echo "Detected MODULE.bazel project - injecting bazel_dep..."

# Append bazel_dep and extension setup to MODULE.bazel
cat >> MODULE.bazel <<'EOF'

# BuildBuddy RBE toolchain (injected by qa_test_runner.sh)
bazel_dep(name = "toolchains_buildbuddy", version = "0.0.2")

# Use the extension to create toolchain and platform targets
buildbuddy = use_extension("@toolchains_buildbuddy//:extensions.bzl", "buildbuddy")

# Workaround: toolchains_buildbuddy loads buildifier_prebuilt but declares it as dev_dependency
bazel_dep(name = "buildifier_prebuilt", version = "8.2.0.2")
EOF
echo "MODULE.bazel updated successfully with bazel_dep and extension"

# Generate unique invocation ID
invocation_id=$(uuidgen 2>/dev/null || cat /proc/sys/kernel/random/uuid 2>/dev/null || echo "test-$(date +%s)")

# Enable bzlmod (always, since we only support bzlmod projects)
echo "Enabling bzlmod mode"
bazel_mode_flags="--enable_bzlmod --noenable_workspace"

# Create .bazelrc with remote execution configuration (remove existing to avoid conflicts)
echo "Creating .bazelrc for remote execution..."
rm -f .bazelrc
cat > .bazelrc <<EOF

# QA Integration Test Configuration (auto-generated by qa_test_runner.sh)
build:qa_integration_test ${bazel_mode_flags}
build:qa_integration_test --remote_executor=grpcs://buildbuddy.buildbuddy.dev
build:qa_integration_test --remote_cache=grpcs://buildbuddy.buildbuddy.dev
build:qa_integration_test --bes_backend=grpcs://buildbuddy.buildbuddy.dev
build:qa_integration_test --bes_results_url=https://buildbuddy.buildbuddy.dev/invocation/
build:qa_integration_test --remote_timeout=10m
build:qa_integration_test --jobs=100
build:qa_integration_test --build_metadata=TAGS=qa-integration-test
build:qa_integration_test --invocation_id=${invocation_id}
EOF

# Add platform and toolchain flags for BuildBuddy (using specific Ubuntu GCC x86_64 targets)
cat >> .bazelrc <<EOF
build:qa_integration_test --extra_toolchains=@toolchains_buildbuddy//toolchains/cc:ubuntu_gcc_x86_64
build:qa_integration_test --platforms=@toolchains_buildbuddy//platforms:linux_x86_64
build:qa_integration_test --extra_execution_platforms=@toolchains_buildbuddy//platforms:linux_x86_64
EOF

# Add API key if provided
echo "DEBUG: api_key variable is: '${api_key}'"
if [[ -n "${api_key}" ]]; then
  echo "build:qa_integration_test --remote_header=x-buildbuddy-api-key=${api_key}" >> .bazelrc
  echo "Added API key to .bazelrc"
else
  echo "WARNING: No API key provided (BB_API_KEY environment variable is empty)"
fi

echo "Remote execution configuration created"
echo "Generated .bazelrc content:"
echo "=================================================="
grep -A 20 "QA Integration Test Configuration" .bazelrc || echo "No qa_integration_test config found"
echo "=================================================="

# Run Bazel command
echo "=================================================="
echo "Running Bazel command: ${bazel_command}"
echo "Invocation ID: ${invocation_id}"
echo "=================================================="

# Split command into array for proper execution
set -x
${bazel} ${bazel_command} --config=qa_integration_test
exit_code=$?
set +x

echo "=================================================="
if [[ ${exit_code} -eq 0 ]]; then
  echo "✓ Test PASSED"
  echo "Invocation URL: https://buildbuddy.buildbuddy.dev/invocation/${invocation_id}"
else
  echo "✗ Test FAILED (exit code: ${exit_code})"
  echo "Invocation URL: https://buildbuddy.buildbuddy.dev/invocation/${invocation_id}"
fi
echo "=================================================="

exit ${exit_code}
