load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "util",
    srcs = ["gitutil.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/tools/lint/util",
    visibility = ["//tools/lint:__subpackages__"],
)
