load("//rules/typescript:index.bzl", "ts_library")

ts_library(
    name = "index",
    srcs = ["index.tsx"],
    deps = [
        "//website/theme/BlogPostItem:styles.module.css",
        "@npm//@docusaurus/Link",
        "@npm//@docusaurus/Translate",
        "@npm//@mdx-js/react",
        "@npm//@theme/BlogPostItem",
        "@npm//@theme/MDXComponents",
        "@npm//@theme/Seo",
        "@npm//@types/react",
        "@npm//clsx",
        "@npm//react",
        "@npm//tslib",
    ],
)
