load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//cli:__subpackages__"])

go_library(
    name = "rc_util",
    srcs = ["rc_util.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/cli/parser/rc_util",
    visibility = ["//visibility:public"],
)
