load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "usage_config",
    srcs = ["usage_config.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/enterprise/server/usage/usage_config",
    visibility = ["//visibility:public"],
)
