load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "rlimit",
    srcs = ["rlimit.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/rlimit",
    visibility = ["//visibility:public"],
    deps = ["//server/util/log"],
)
