load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "protodelim",
    srcs = ["protodelim.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/protodelim",
    visibility = ["//visibility:public"],
    deps = ["@org_golang_google_protobuf//proto"],
)
