load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "trace_events",
    srcs = ["trace_events.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/trace_events",
    visibility = ["//visibility:public"],
)
