load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "builtins",
    srcs = ["builtins.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/cli/translate/builtins",
    visibility = ["//visibility:public"],
)

package(default_visibility = ["//cli:__subpackages__"])
