load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "language",
    srcs = ["language.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/cli/fix/language",
    visibility = ["//visibility:public"],
)

package(default_visibility = ["//cli:__subpackages__"])
