load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "lookuplist",
    srcs = ["lookuplist.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/lookuplist",
    visibility = ["//visibility:public"],
    deps = ["//server/util/lookuplist/internal"],
)
