load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "fspath",
    srcs = ["fspath.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/fspath",
    visibility = ["//visibility:public"],
    deps = ["//server/util/log"],
)
