load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "keys",
    srcs = ["keys.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/enterprise/server/raft/keys",
    visibility = ["//visibility:public"],
)
