load("//rules/typescript:index.bzl", "ts_library")

ts_library(
    name = "brands",
    srcs = ["brands.tsx"],
    deps = [
        "//website/src/components/brands:brands.module.css",
        "@npm//@theme/IdealImage",
        "@npm//@types/react",
        "@npm//react",
    ],
)
