load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "testclock",
    srcs = ["testclock.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/testutil/testclock",
    visibility = ["//visibility:public"],
)
