load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "common",
    srcs = ["common.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/cli/common",
)

package(default_visibility = ["//cli:__subpackages__"])
