load("//rules/typescript:index.bzl", "ts_library")

ts_library(
    name = "index",
    srcs = ["index.tsx"],
    deps = [
        "//website/theme/BlogSidebar:styles.module.css",
        "@npm//@docusaurus/Link",
        "@npm//@theme/BlogSidebar",
        "@npm//@types/react",
        "@npm//clsx",
        "@npm//react",
    ],
)
