#!/usr/bin/env bash

# Dev QA Test Runner for rules_bazel_integration_test
# This script downloads a source tarball, injects BuildBuddy toolchain,
# and runs Bazel commands against it using BuildBuddy RBE.

set -euo pipefail

bazel="${BIT_BAZEL_BINARY:-}"
workspace_dir="${BIT_WORKSPACE_DIR:-}"

tarball_url="${QA_TARBALL_URL:-}"
strip_prefix="${QA_STRIP_PREFIX:-}"
bazel_command="${QA_BAZEL_COMMAND:-}"
api_key="${BB_API_KEY:-}"
bb_endpoint="${BB_ENDPOINT:-buildbuddy.buildbuddy.dev}"

if [[ -z "${bazel}" ]]; then
  echo >&2 "ERROR: BIT_BAZEL_BINARY not set"
  exit 1
fi

if [[ -z "${workspace_dir}" ]]; then
  echo >&2 "ERROR: BIT_WORKSPACE_DIR not set"
  exit 1
fi

if [[ -z "${tarball_url}" ]]; then
  echo >&2 "ERROR: QA_TARBALL_URL not set"
  exit 1
fi

if [[ -z "${strip_prefix}" ]]; then
  echo >&2 "ERROR: QA_STRIP_PREFIX not set"
  exit 1
fi

if [[ -z "${bazel_command}" ]]; then
  echo >&2 "ERROR: QA_BAZEL_COMMAND not set"
  exit 1
fi

echo "=================================================="
echo "Dev QA Test Runner"
echo "=================================================="
echo "Bazel binary: ${bazel}"
echo "Workspace: ${workspace_dir}"
echo "Tarball URL: ${tarball_url}"
echo "Strip prefix: ${strip_prefix}"
echo "Bazel command: ${bazel_command}"
echo "=================================================="

cd "${workspace_dir}"

if ! curl -L "${tarball_url}" -o repo.tar.gz; then
  echo >&2 "ERROR: Failed to download tarball from ${tarball_url}"
  exit 1
fi

if ! tar -xzf repo.tar.gz; then
  echo >&2 "ERROR: Failed to extract tarball"
  exit 1
fi

if [[ ! -d "${strip_prefix}" ]]; then
  echo >&2 "ERROR: Expected directory ${strip_prefix} not found after extraction"
  ls -la
  exit 1
fi

cd "${strip_prefix}"
echo "Working directory: $(pwd)"

if [[ ! -f MODULE.bazel ]]; then
  echo >&2 "ERROR: No MODULE.bazel found. Only bzlmod projects are supported."
  exit 1
fi

if [[ "${INJECT_TOOLCHAIN:-true}" == "true" ]]; then
  echo "Detected MODULE.bazel project - injecting bazel_dep..."

  # Append bazel_dep and extension setup to MODULE.bazel
  cat >> MODULE.bazel <<'EOF'

# BuildBuddy RBE toolchain (injected by qa_test_runner.sh)
bazel_dep(name = "toolchains_buildbuddy", version = "0.0.4")

# Use the extension to create toolchain and platform targets
buildbuddy = use_extension("@toolchains_buildbuddy//:extensions.bzl", "buildbuddy")
EOF
  echo "MODULE.bazel updated successfully with bazel_dep and extension"
else
  echo "Skipping toolchain injection (INJECT_TOOLCHAIN=false)"
fi

# Enable bzlmod (always, since we only support bzlmod projects)
echo "Enabling bzlmod mode"
bazel_mode_flags="--enable_bzlmod --noenable_workspace"

# Append dev QA test configuration to .bazelrc (preserves existing configuration)
echo "Appending remote execution configuration to .bazelrc..."
cat >> .bazelrc <<EOF

# Dev QA Test Configuration (auto-generated by dev_qa_test_runner.sh)
build:dev_qa_test ${bazel_mode_flags}
build:dev_qa_test --remote_executor=grpcs://${bb_endpoint}
build:dev_qa_test --remote_cache=grpcs://${bb_endpoint}
build:dev_qa_test --bes_backend=grpcs://${bb_endpoint}
build:dev_qa_test --bes_results_url=https://${bb_endpoint}/invocation/
build:dev_qa_test --remote_timeout=10m
build:dev_qa_test --jobs=100
build:dev_qa_test --build_metadata=TAGS=qa-integration-test
build:dev_qa_test --workspace_status_command=
build:dev_qa_test --compilation_mode=fastbuild
build:dev_qa_test --host_compilation_mode=fastbuild
build:dev_qa_test --test_tag_filters=-block-network
EOF

cat >> .bazelrc <<EOF
build:dev_qa_test --extra_toolchains=@toolchains_buildbuddy//toolchains/cc:ubuntu_gcc_x86_64
build:dev_qa_test --platforms=@toolchains_buildbuddy//platforms:linux_x86_64
build:dev_qa_test --extra_execution_platforms=@toolchains_buildbuddy//platforms:linux_x86_64
EOF

if [[ -n "${api_key}" ]]; then
  echo "build:dev_qa_test --remote_header=x-buildbuddy-api-key=${api_key}" >> .bazelrc
  echo "Added API key to .bazelrc"
else
  echo "WARNING: No API key provided (BB_API_KEY environment variable is empty)"
fi

echo "Remote execution configuration created"
echo "=================================================="

if [[ "${UPDATE_LOCKFILE:-true}" == "true" ]]; then
  echo "Updating lockfile with injected BuildBuddy toolchain..."
  ${bazel} mod deps --lockfile_mode=update
  echo "Lockfile updated successfully"
  echo "=================================================="
else
  echo "Skipping lockfile update (UPDATE_LOCKFILE=false)"
  echo "=================================================="
fi

echo "Running Bazel command: ${bazel_command}"
echo "=================================================="

set -x
${bazel} ${bazel_command} --config=dev_qa_test
exit_code=$?
set +x

echo "=================================================="
if [[ ${exit_code} -eq 0 ]]; then
  echo "✓ Test PASSED"
else
  echo "✗ Test FAILED (exit code: ${exit_code})"
fi
echo "=================================================="

exit ${exit_code}
