load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "sparse",
    srcs = ["set.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/codesearch/sparse",
    visibility = ["//visibility:public"],
)
