load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "vfscommon",
    srcs = ["vfscommon.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/enterprise/server/util/vfscommon",
    visibility = ["//visibility:public"],
)

package(default_visibility = ["//enterprise:__subpackages__"])
