load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "firecracker_util",
    srcs = ["firecracker_util.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/enterprise/server/util/firecracker_util",
    visibility = ["//visibility:public"],
)

package(default_visibility = ["//enterprise:__subpackages__"])
