// Package mcptools defines the tool manifest format that gets generated by
// mcptoolgen from api/v1/service.proto and embedded into the MCP server,
// along with the explicit allowlist of API RPCs that may be exposed over MCP.
package mcptools

import "encoding/json"

// allowedRPCs is the reviewed set of public API methods currently exposed via
// MCP. Keep this list intentionally small and expand it one method at a time.
var allowedRPCs = map[string]struct{}{
	"GetInvocation": {},
	"GetLog":        {},
	"GetTarget":     {},
	"GetAction":     {},
	"GetFile":       {},
}

// Manifest is the generated inventory of API-backed MCP tools.
type Manifest struct {
	// Tools contains one entry per unary public API method exposed via MCP.
	Tools []Tool `json:"tools"`
}

// Tool describes one generated MCP tool backed by a public API method.
type Tool struct {
	// Name is the MCP tool name presented to clients.
	Name string `json:"name"`
	// RPCName is the ApiService method name invoked when the tool is called.
	RPCName string `json:"rpcName"`
	// RequestType is the fully qualified protobuf request message name.
	RequestType string `json:"requestType"`
	// ResponseType is the fully qualified protobuf response message name.
	ResponseType string `json:"responseType"`
	// Description is the human-readable tool description shown in tools/list.
	Description string `json:"description,omitempty"`
	// ReadOnly reports whether the tool is expected to avoid mutations.
	ReadOnly bool `json:"readOnly,omitempty"`
	// InputSchema is the MCP JSON Schema for the tool arguments.
	InputSchema json.RawMessage `json:"inputSchema"`
}

// AllowsRPC reports whether the given public API RPC may be exposed over MCP.
func AllowsRPC(rpcName string) bool {
	_, ok := allowedRPCs[rpcName]
	return ok
}
