load("@npm_bazel_typescript//:index.bzl", "ts_library")

package(default_visibility = ["//visibility:public"])

ts_library(
    name = "animated_value",
    files = ["animated_value.ts"],
    deps = [
        "@npm//tslib",
    ]
)

ts_library(
    name = "animation_loop",
    files = ["animation_loop.ts"],
    deps = [
        "@npm//tslib",
    ]
)

ts_library(
    name = "dom",
    files = ["dom.ts"],
    deps = [
        "@npm//tslib",
    ]
)

ts_library(
    name = "time_delta",
    files = ["time_delta.ts"],
    deps = [
        "@npm//tslib",
    ]
)

ts_library(
    name = "math",
    files = ["math.ts"],
    deps = [
        "@npm//tslib",
    ]
)

ts_library(
    name = "memo",
    files = ["memo.ts"],
    deps = [
        "@npm//tslib",
    ]
)