load("//rules/typescript:index.bzl", "ts_library")

ts_library(
    name = "enterprise",
    srcs = ["enterprise.tsx"],
    deps = [
        "//website/src/components/enterprise:enterprise.module.css",
        "//website/src/css:common.module.css",
        "@npm//@types/react",
        "@npm//lucide-react",
        "@npm//react",
    ],
)
