load("//rules/typescript:index.bzl", "ts_library")

ts_library(
    name = "globe",
    srcs = ["globe.tsx"],
    deps = [
        "//website/src/components/globe:globe.module.css",
        "@npm//@docusaurus/ExecutionEnvironment",
        "@npm//@types/react",
        "@npm//react",
    ],
)
