load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "random",
    srcs = ["random.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/v2/server/util/random",
    visibility = ["//visibility:public"],
    deps = ["//server/util/log"],
)
