load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "build_buddy_url",
    srcs = ["build_buddy_url.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/endpoint_urls/build_buddy_url",
    visibility = ["//visibility:public"],
    deps = ["//server/util/flagutil/types"],
)
