load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "blocklist",
    srcs = ["blocklist.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/blocklist",
    visibility = ["//visibility:public"],
)
