load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "indexprofile",
    srcs = ["indexprofile.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/codesearch/indexprofile",
    visibility = ["//visibility:public"],
    deps = ["//server/util/log"],
)
