#!/usr/bin/env bash
# go-to-definition can take us to files outside the bazel workspace where bazel
# cannot be run, so cd back to the workspace root.
SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
cd $SCRIPT_DIR/..
exec bazel run -- @io_bazel_rules_go//go/tools/gopackagesdriver "${@}"
