module.exports = {
  someSidebar: {
    "Getting Started": ["introduction", "cloud", "on-prem", "contributing"],
    Guides: ["guides", "guide-auth", "guide-metadata"],
    "Remote Build Execution": [
      "remote-build-execution",
      "rbe-setup",
      "rbe-platforms",
      "secrets",
      "rbe-microvms",
      "rbe-github-actions",
      "rbe-pools",
    ],
    "Workflows (CI)": ["workflows-introduction", "workflows-setup", "workflows-config"],
    CLI: ["cli", "cli-plugins"],
    Troubleshooting: ["troubleshooting", "troubleshooting-rbe", "troubleshooting-slow-upload"],
    Enterprise: [
      "enterprise",
      "enterprise-setup",
      "enterprise-config",
      "enterprise-helm",
      "enterprise-rbe",
      "enterprise-mac-rbe",
      "enterprise-api",
    ],
    Monitoring: ["prometheus-metrics"],
    Architecture: [
      "architecture-overview",
      "architecture-data-storage",
      "architecture-build-event-write",
      "architecture-build-event-read",
      "architecture-cache-write",
      "architecture-cache-read",
      "architecture-remote-execution",
      "architecture-self-hosted-executor",
    ],
    Configuration: [
      "config",
      "config-samples",
      "config-app",
      "config-database",
      "config-storage",
      "config-cache",
      "config-github",
      "config-ssl",
      "config-auth",
      "config-integrations",
      "config-org",
      "config-rbe",
      "config-misc",
      "config-api",
      "config-telemetry",
      "config-flags",
      "config-all-options",
    ],
  },
};
