load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "histogram",
    srcs = ["histogram.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/histogram",
    visibility = ["//visibility:public"],
)
