load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "constants",
    srcs = ["constants.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/enterprise/server/raft/constants",
    visibility = ["//visibility:public"],
    deps = ["//enterprise/server/raft/keys"],
)
