load("//rules/typescript:index.bzl", "ts_library")

ts_library(
    name = "apply",
    srcs = ["apply.tsx"],
    deps = [
        "//website/src/css:common.module.css",
        "//website/src/pages:contact.module.css",
        "//website/src/util:message",
        "@npm//@types/react",
        "@npm//react",
    ],
)
