load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//enterprise:__subpackages__"])

go_library(
    name = "providerips",
    srcs = ["providerips.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/enterprise/server/util/trafficstats/providerips",
    visibility = ["//visibility:public"],
)
