FROM gcr.io/flame-public/buildbuddy-executor-enterprise:latest

# Install GCC, make
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential \
      && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
