load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "ports",
    srcs = ["ports.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/enterprise/server/remote_execution/llmproxy/ports",
)
