load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "urlutil",
    srcs = ["urlutil.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/urlutil",
    visibility = ["//visibility:public"],
)
