load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "canary",
    srcs = ["canary.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/canary",
    visibility = ["//visibility:public"],
    deps = ["//server/util/log"],
)
