name: "Build Linux arm64 Github Release Artifacts"

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: "Git branch to checkout."
        required: true
        default: "master"
        type: string
      version_tag:
        description: "Version to tag release artifacts."
        required: true
        type: string
  workflow_call:
    inputs:
      release_branch:
        description: "Git branch to checkout."
        required: true
        type: string
      version_tag:
        description: "Version to tag release artifacts."
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04-16cpu-arm64-arm-limited
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          ref: ${{ inputs.release_branch }}
          # We need to fetch git tags to obtain the latest version tag to report
          # the version of the running binary.
          fetch-depth: 0

      - name: Build and Upload Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bazelisk build --config=release --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_ORG_API_KEY }} //enterprise/server/cmd/executor:executor
          cp bazel-bin/enterprise/server/cmd/**/**/executor executor-enterprise-linux-arm64
          gh release upload ${{ inputs.version_tag }} executor-enterprise-linux-arm64 --clobber
