name: "CI (BuildBuddy on GitHub Actions)"
on:
  pull_request:
    branches:
      - "master"
jobs:
  bazel-test:
    name: "bazel test"
    runs-on: buildbuddy-dev
    steps:
      - name: "Print debug info"
        run: |
          echo "Bazel processes:"
          ps aux | grep bazel

          echo "Environment:"
          env | grep -v JITCONFIG

          echo "Generated ~/.bazelrc:"
          cat ~/.bazelrc

      # Note: actions/checkout supports syncing an existing repo, so this step
      # should do minimal work in the case where we're resuming from a snapshot.
      - name: "Checkout buildbuddy-io/buildbuddy"
        uses: actions/checkout@v4
        with:
          path: buildbuddy

      - name: "Test"
        run: |
          cd buildbuddy
          # Setting RUNNER_TRACKING_ID prevents the runner from
          # killing the bazel server at the end of the job.
          # See https://github.com/actions/runner/issues/598
          # TODO: set this automatically.
          RUNNER_TRACKING_ID="" bazelisk test //... --config=linux-workflows
