name: PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore caches
        id: restore-caches
        uses: ./.github/actions/cache-restore
        with:
          repo-cache-dir: ~/repo-cache/untrusted/

      - name: Test
        env:
          GO_REPOSITORY_USE_HOST_CACHE: 1
          GOMODCACHE: /home/runner/go-mod-cache
        run: |
          bazelisk test \
            --config=untrusted-ci \
            --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_ORG_API_KEY }} \
            //...

      - name: Save caches
        uses: ./.github/actions/cache-save
        if: always()
        with:
          repo-cache-hit: ${{ steps.restore-caches.outputs.repo-cache-hit }}
          go-mod-cache-hit: ${{ steps.restore-caches.outputs.go-mod-cache-hit }}
          yarn-cache-hit: ${{ steps.restore-caches.outputs.yarn-cache-hit }}
