name: PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          bazelisk build --config=untrusted-ci //...

      - name: Test
        run: |
          bazelisk test --config=untrusted-ci //...
