name: PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout buildbuddy
        uses: actions/checkout@v3
        with:
          path: buildbuddy

      - name: Checkout buildbuddy-internal
        uses: actions/checkout@v3
        with:
          path: buildbuddy-internal
          repository: 'buildbuddy-io/buildbuddy-internal'

      - name: Configure buildbuddy-internal
        run: |
          echo "build --override_repository=com_github_buildbuddy_io_buildbuddy=${GITHUB_WORKSPACE}/buildbuddy" >> ${GITHUB_WORKSPACE}/buildbuddy-internal/user.bazelrc

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Build buildbuddy
        run: |
          "cd ${GITHUB_WORKSPACE}/buildbuddy && ${GITHUB_WORKSPACE}/bin/bazel" build --config=untrusted-ci //...

      - name: Build buildbuddy-internal
        run: |
          "cd ${GITHUB_WORKSPACE}/buildbuddy-internal && ${GITHUB_WORKSPACE}/bin/bazel" build --config=untrusted-ci //...

      - name: Test buildbuddy
        run: |
          "cd ${GITHUB_WORKSPACE}/buildbuddy && ${GITHUB_WORKSPACE}/bin/bazel" test --config=untrusted-ci //...
