name: Remote Bazel CI

on:
  pull_request:
    branches:
      - master
    paths:
      - "cli/remotebazel/**"

jobs:
  build:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BUILDBUDDY_GITHUB_USER_TOKEN }}

      - name: Build the cli from the pushed ref
        run: |
          bazelisk build cli \
            --config=remote \
            --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_ORG_API_KEY }}

      - name: Run remote bazel using locally built cli
        run: |
          $PWD/bazel-bin/cli/cmd/bb/bb_/bb --verbose=1 remote --env=GIT_REPO_DEFAULT_BRANCH=master test //... \
            --config=linux-workflows --config=race \
            --remote_executor=grpcs://buildbuddy.buildbuddy.io \
            --test_tag_filters=-performance,-webdriver,-docker,-bare \
            --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_ORG_API_KEY }}
