name: "Tag release branch updates"

on:
  push:
    branches:
      - "bb_release_*"

jobs:
  tag:
    # The internal cut-release workflow creates the initial minor-version tag.
    if: ${{ !github.event.created && !github.event.deleted && !github.event.forced }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          ref: ${{ github.event.after }}
          fetch-depth: 0
          token: ${{ secrets.BUILDBUDDY_GITHUB_USER_TOKEN }}

      - name: Create patch version tag
        run: |
          git config --local user.email "github-actions-release-bot@users.noreply.github.com"
          git config --local user.name "github-actions-release[bot]"
          ./release.py --auto --force --bump_version_type=patch
