name: Build Website

on:
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/website-pr.yaml"
      - "docs/**"
      - "website/**"
      - "server/metrics/**"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'website skip')"

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Setup Bazel Go module cache
        uses: ./.github/actions/setup-bazel-go-mod-cache

      - name: Build Website
        run: |
          API_KEY="${{ secrets.BUILDBUDDY_ORG_API_KEY }}"
          if [[ "$API_KEY" ]]; then
            echo >>user.bazelrc "common --config=ci --remote_header=x-buildbuddy-api-key=$API_KEY"
          else
            echo >>user.bazelrc "common --config=ci-anon"
          fi
          bazelisk build --repository_cache='~/repo-cache/' //website:website
