name: Update Website

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - "website/**"
      - "server/metrics/**"
      - "enterprise/server/backends/prom/**"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'website skip')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Restore caches
        id: cache-restore
        uses: ./.github/actions/cache-restore

      - name: Build Website
        env:
          GO_REPOSITORY_USE_HOST_CACHE: 1
          GOMODCACHE: /home/runner/go-mod-cache
        run: |
          bazelisk build --repository_cache='~/repo-cache/' //website:website --config=ci --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_ORG_API_KEY }}
          rm -rf website/build
          mkdir -p website/build
          cd website/build
          tar -xf ../../bazel-bin/website/website.tar
          touch .nojekyll

      - name: Deploy Website 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: website/build

      - name: Build notification if there are new changelog entries
        id: changelog-msg
        shell: bash
        run: |
          prev_sha="${{ github.event.before }}"
          modified_changelog_files=$(
            git diff --name-status "$prev_sha" "${{ github.sha }}" -- "website/changelog/*.md" "website/changelog/*.mdx" \
              | awk '$1 == "A" {print $2}'
          )

          if [[ -z "$modified_changelog_files" ]]; then
            echo "No newly added changelog entries."
            exit 0
          fi

          msg="*New changelog entries added:*\n"
          while IFS= read -r file; do
            [[ -z "$file" ]] && continue
            slug="$(basename "$file")"
            slug="${slug%.*}"
            msg="${msg}• https://www.buildbuddy.io/changelog/${slug}\n"
          done <<< "$modified_changelog_files"

          {
            echo "text<<EOF"
            echo -e "$msg"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Post to Slack
        if: steps.changelog-msg.outputs.text != ''
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              attachments: [{
                color: '#1f883d',
                text: `${{ steps.changelog-msg.outputs.text }}`
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CHANGELOG_WEBHOOK_URL }}

      - name: Save caches
        uses: ./.github/actions/cache-save
        if: always()
        with:
          repo-cache-dir: ${{ steps.cache-restore.outputs.repo-cache-dir }}
          go-mod-cache-dir: ${{ steps.cache-restore.outputs.go-mod-cache-dir }}
          yarn-cache-dir: ${{ steps.cache-restore.outputs.yarn-cache-dir }}
