apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prom
    isDefault: true
    url: http://host.docker.internal:9100
    version: 1
    editable: false
    jsonData:
      timeInterval: 1s
