apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    uid: vm
    isDefault: true
    url: ${GF_DATASOURCE_URL}
    version: 1
    editable: false
    jsonData:
      timeInterval: 1s
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    jsonData:
      port: ${CLICKHOUSE_PORT}
      host: host.docker.internal
      username: ${CLICKHOUSE_USERNAME}
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
