apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    uid: vm
    isDefault: true
    url: ${GF_DATASOURCE_URL}
    version: 1
    editable: false
    jsonData:
      timeInterval: 1s
